### ISSUE TITLE
exitAfterHook() issue

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#106]
I have a hook_survey_page_top function in an EM that calls a built-in REDCap function that ultimately calls the 'redirect' function.  This function has an exit(); statement (init_functions.php).

So, when my EM/hook runs, I get an error message:

```
The 'hook_survey_page_top' hook did not complete for the 'autocontinue_logic' module, but a specific cause could not be detected.  This could be caused by a die() or exit() call in the module, either of which should be removed to allow other module hooks to continue executing.  This could also be caused by a killed duplicate query initiated via db_query().  All queries should be made via $module->query() so that duplicate queries can de detected and ignored. 
```

So, I added `$this->exitAfterHook();` before any of this but it didn't make a difference.  I still get the error messages.  Is this intended?  Shouldn't this prevent the EM from throwing the error?

**Comment by 123andy** [comment]
I was able to get around this by rewriting the REDCap function I was using to do a soft redirect and return instead of exit, but wondering if there should be an option from inside an EM to set a flag that allows a hook to 'exit' without the the register_shutdown_function throwing an error.

Not sure how to do this since it resides in a static parent method...

Maybe something like:

```php
register_shutdown_function(function () {
	$activeModulePrefix = self::getActiveModulePrefix();

	if ($activeModulePrefix == null) {
		// A fatal error did not occur in the middle of a module operation.
		return;
	}

	if (!empty($_GLOBALS['OVERRIDE_EM_SHUTDOWN_ERROR'][$activeModulePrefix]) {
		// The EM explicitly requested that there should be no errors here
		unset ($_GLOBALS['OVERRIDE_EM_SHUTDOWN_ERROR'][$activeModulePrefix]);  
		return;
	}
...
```

Then, in your EM you could simple add this:
```php
  // I know this will cause the hook to exit, so I want to override the shutdown error:
  array_push($_GLOBALS['OVERRIDE_EM_SHUTDOWN_ERROR'], $this->PREFIX);
  exit();
```
Thoughts?  I'm sure there is a better way.

**Comment by mmcev106** [comment]
Calling `$this->exitAfterHook()` should be all you have to do.  The framework will call `exit()` for you once all modules have finished executing for the current hook.  Modules should not call `exit()` directly because module execution order is undefined, and we don't want code it one module to have to ability to prevent another from running (unless the other module specifically allows it through a flag or something).  I'll go ahead and close this, but please feel free to comment/reopen if that doesn't take care of it for you.

**Comment by 123andy** [comment]
Hi Mark,

I think the real issue is that there places in REDCap proper where the code exits instead of returning (such as end of survey messages, etc...)  so you can get caught in a bit of a bind where you really DO intend for this EM to quit the process.  I realize that could be problematic if you had other EMs working off the same hook, but there should probably be a method for overriding the error (caveat emptor).

**Comment by mmcev106** [comment]
I'm not sure I understand the use case.  Can you describe it in more detail?  Is there another way to achieve a similar result without stopping the process and preventing other modules from running?

**Comment by mmcev106** [comment]
@123andy, I think I'm going close this since it hasn't changed in six months.  Feel free to re-open it if you have a different vision for `exit()` support.
