### ISSUE TITLE
How to do Internationalization and Localization in modules

### ISSUE THREAD

**Issue by pbchase** [vanderbilt/redcap-external-modules#107]
Have their been any discussions about how to do internationalization and localization in modules? For those not familiar with these terms they refer to the ability to support multiple languages (internationalization) and the support for a specific language (localization). If a software developer does the former well, a bilingual speaker can translate the text strings used in the software to another language to do the latter for that language.

In our modules, we have been doing "internationalization light". We provide fields to configure some of the strings used by the module. We might provide a built-in default text in English or leave them entirely blank and provide a well-honed English example in the README. Typically we do this on modules that need a template. You can see such an example in our module [Report Production Candidates](https://github.com/ctsit/report_production_candidates)

That said, our modules are mostly hard-coded in US English with no internationalization support. I am curious to know if others have addressed this in a more scalable, more consistent way.

**Comment by mmcev106** [comment]
https://community.projectredcap.org/questions/45861/how-to-do-internationalization-and-localization-in.html
