### ISSUE TITLE
System ONLY level modules displayed at project level

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#109]
If a external module should only be available to system administrators it should not be visible nor list in a project's external module area.

**Example 1:**
The Instance Marker when turned on at the system level is display at the project level for users.  Mr. S. Banks, the administrator, was surprised when a user called him and asked about the "Instance Marker" module and what it does.  

**Example 2:**
Some module's are not appropriate to display to end users.  For example the Admin Dashboard which provides information about users should not be visible/displayed to individual projects.

**Comment by biggeeves** [comment]
**Example Problem:**  When REDCap is updated from a version without the "init" method to one with the "init" method and an external module has a method that matches the new "inti" method than REDCap will fail to start, instead throwing a fatal error.  Deleting the external module does not fix the problem as load balancing simply reloads the module.  The only solution currently available is to turn off the external module via SQL.  

**Possible Solutions:**
**1)** Add "?external_modules=0" to the URL, which would turn off all external modules and allow REDCap to load.  This would be a system administrator only parameter.  Then the system admin could go to external modules and disable the problematic module. 

**2)** When a new method is added to external modules scan all available modules for the new method name and if a collision is found require the author to update.

**3)** Is it possible to detect the fatal error and then disable the problematic external module?

**4)** Publish a fix for this in the directions: The fix?: Locate the problematic external module folder, delete the contents in the folder and try REDCap again.  Will keeping the folder will _not_ trigger the automatic load balancing download?

**5)**  Remove external modules that have a known fatal error from the "module marker".

**9)** Other

**Comment by 123andy** [comment]
I like the idea of super-users being able to catch the instantiation error and get more details and perhaps re-load without EMs enabled...   Would that trigger an alert to all projects with EMs that they were temporarily disabled?

Somewhat related to this, @mcguffk and I were talking about the need to have an 'enabled' status of -1 for those modules that are disabled due to error, so when viewing the EMs in the control center you could quickly discern those that failed due to errors...

**Comment by mmcev106** [comment]
For future reference, the discussion on issues like the "init" conflict has moved here:Z
https://github.com/vanderbilt/redcap-external-modules/issues/112

**Comment by mmcev106** [comment]
I think the details around this scenario have since changed.  Closing...  Feel free to reopen.
