### ISSUE TITLE
Issue with loading classes from upgrade folder

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#111]
We are on 8.6.5 and testing out 8.7.1 on our dev server.  The upgrade webfolder for 8.7.1 made it onto your production server even though the upgrade hasn't yet taken place and the database is still set to 8.6.5.  

We started getting these error messages:

Error Message: Cannot redeclare cleanHtml2() (previously declared in /var/www/html/redcap_v8.7.1/Config/init_functions.php:4398)
File: /var/www/html/redcap_v8.6.5/Config/init_functions.php

I'm thinking that init functions for 8.7.1 should not be getting loaded but is because some filesystem scan is overriding the setting in redcap_config...  

I'm out of town so can't troubleshoot at the moment but wondering if others have seen this?

**Comment by 123andy** [comment]
Looks like it is the cron.php that is causing this to fire for many use cases...

**Comment by mmcev106** [comment]
I have not seen this.  I'll mention @taylorr4 to make sure he sees this (not sure if he monitors all issues here).

**Comment by 123andy** [comment]
You are cor.. Uh.  You are corr.. ..  Damn this is hard to say.  You're cor-huhum-rect, @taylorr4.  My non-versioned files were out of date.  I just updated and will test if it recurs.  Thanks!
