### ISSUE TITLE
Important issue with database performance

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#113]
Hi @mmcev106 - we were seeing a lot of database queries coming from external modules - dozens per  second - all very similar.  They were showing up in the mysql dashboard as transient processes.  The queries are quick but when you have hundreds of them they were creating a burden on our servers... 
 I found an issue in the way that the cache was built and verified in the EM class that is partly to blame.  

Here is an example of the data pulled from settings to tell which EMs and versions are active. 
```
                // ENABLED IN PROJ 16
                [directory_prefix] => shazam
                [project_id] => 16
                [key] => enabled
                [value] => true
                [type] => boolean

                // NOT ENABLED GLOBALLY
                [directory_prefix] => shazam
                [project_id] =>
                [key] => enabled
                [value] => false
                [type] => boolean

                // VERSION NUMBER ENABLED
                [directory_prefix] => shazam
                [project_id] =>
                [key] => version
                [value] => v9.9.9
                [type] => string
```
The next step was to verify that the version is correct and present, but this verification was also being done on the 'enabled' records in this array.  So, if you had an EM enabled on 20 projects, it was being verified 20 times.  19 of them did not include the version number so it was leading to an extra database query for each of them to determine the version number....  Anyhow - I made a quick patch and pushed it as the 'performance-fix' branch.  I think needs just a quick test run and then should be expedited as we saw a pretty dramatic increase in performance afterwards...)

54337f8dcb77dbb110b68db5fe435b8aa45b11ea

**Comment by 123andy** [comment]
I wasn't sure what branch to make a pull request - hence this issue...

**Comment by mmcev106** [comment]
This definitely looks like a significant performance improvement!  Thanks **VERY** much for the time spent diagnosing this and creating a solution!!!  I went ahead and merged it into the **testing** branch (and removed the **performance-fix** branch).  I believe it's a safe change, but I'd prefer to err on the side of caution and let it sit on our test server for a week before going to production.  @taylorr4, I suspect this will measurably reduce our database load as well.  Let me know if you'd to discuss moving it to production sooner.  I'll go ahead and close this issue, but feel free to reopen it if anyone would like to discuss this further.

**Comment by taylorr4** [comment]
Yes, thanks, @123andy! @mmcev106, i'll plan on integrating it into REDCap next week probably when we've tested it some and once you've pushed it to prod branch. Thanks!
