### ISSUE TITLE
Add an option to prevent External Module settings from being copied when copying a project

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#118]
This will need to be made in the REDCap core code (not this repo), but this is the best place to keep track of it for now.

**Comment by taylorr4** [comment]
@mmcev106 this was a pretty simple add and makes sense. I've already added it to REDCap 8.7.3 (https://github.com/vanderbilt/REDCap/commit/6a077ada99358c5ac2a8ae250421b67d5aac3fb1)
