### ISSUE TITLE
Interesting exception difference between native and api urls...

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#121]
I'm trying to methodically test permissions to come up with a good plan re: urls...

I noticed that if I have an em page (cc_test) that is NOT in the 'no-auth-pages' array:

http://localhost/redcap_v8.7.3/ExternalModules/?prefix=permission_test&page=cc_test&NOAUTH
returns a standard exception:
```
Fatal error: Uncaught Exception: The NOAUTH parameter is not allowed on this page. in /var/www/html/redcap_v8.7.3/ExternalModules/index.php:33 Stack trace: #0 {main} thrown in /var/www/html/redcap_v8.7.3/ExternalModules/index.php on line 33
REDCap crashed due to an unexpected fatal error!

Please try again what you were doing. If this error persists, please contact a REDCap administrator. We apologize for any inconvenience.
```
But, the equivalent API-based url throws a real error and I can't figure out which file they are talking about with line 2/column 1:  Any ideas @mmcev106 ?

http://localhost/api/?type=module&prefix=permission_test&page=cc_test&NOAUTH

```
This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
```

So clearly this is something different in the bootstrap process...

**Comment by mmcev106** [comment]
If you view the source when the browser shows the "contains the following errors" message, you should see the same exception as the first URL.  I think the API simply wraps the exception is a way that confuses the browser, and it doesn't render the exception in the source.  Does that answer your question?

**Comment by 123andy** [comment]
Ah - that makes sense.  Looks like there might be a logic error in the System class
```php
			// API error only
			if (defined('PAGE') && (PAGE == "api/index.php" || PAGE == "API/index.php") && (!isset($_GET['type']) || $_GET['type'] != 'module'))
			{
				API::outputApiErrorMsg('An unknown error occurred. Please check your API parameters.');
			}
```

In the api/index.php file, $_GET['type'] is UNSET before the externalmodules/index.php file is included so this last part of logic doesn't apply and you get the XML...

Should this be something like?
```php
			// API error only
			if (defined('PAGE') && (PAGE == "api/index.php" || PAGE == "API/index.php") && (!isset($_GET['type']) || $_GET['type'] != 'module'))
			{
				if (defined('APP_PATH_EXTMOD')) exit();
				API::outputApiErrorMsg('An unknown error occurred. Please check your API parameters.' . PAGE);
			}
```

**Comment by mmcev106** [comment]
...perhaps another good example for the benefits of a version-less endpoint that leaves as much as possible up to ExternalModules/index.php.

**Comment by 123andy** [comment]
Or maybe:
```
			// API error only
			if (defined('PAGE') && (PAGE == "api/index.php" || PAGE == "API/index.php") && (!isset($_GET['type']) || $_GET['type'] != 'module'))
			{
                if (defined('APP_PATH_EXTMOD')) {
                    ob_end_clean();
                    API::outputApiErrorMsg($message);
                }
                API::outputApiErrorMsg('An unknown error occurred. Please check your API parameters.');
			}
```

**Comment by taylorr4** [comment]
@123andy if you feel confident in those and you've had a chance to test either of those changes suggested above, then do you mind submitting them as a pull request to the REDCap repo. Thanks!

**Comment by mmcev106** [comment]
Closing, since this hasn't been updated in over a year.  Feel free to reopen.
