### ISSUE TITLE
Enforce module directory name (a.k.a. prefix) standards

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#131]
This would ensure that two prefixes for the same module couldn't be deployed at the same time (typically a manually deployment and a repo deployment, dashes vs. underscores vs. camelCase, etc.).  We should think this through more though.  There may be a better solution.

**Comment by 123andy** [comment]
My vague recollection was that you could have the same module in multiple module directories and the lookup function will just route to the module that is found first (should the version numbers be identical).  In general, this means the version in the default "modules" and then in the order as provided in the config setting... 

As an example, I might have the 'official' version from the repo in my 'modules' directory and then have the same module tied to a local git repo in my 'modules-local' directory but at a different version number.

/modules/shazam_v1.2.3/...
/modules-local/shazam_v9.9.9/...

Am I missing something?

**Comment by mmcev106** [comment]
The situation we've run into a few times now is a subtle name difference leading to confusion and the same module being deployed multiple times.  For example, a prefix of "someModule" vs. "some_module" vs. "some-module".  If they have the same version, is it unclear which is which on the enable pages.

**Comment by mmcev106** [comment]
In our case it was not a conflict, but perhaps the v9.9.9 version would have been noticed and caused the admin to think twice before disabling it and enabling the version from the repo (effectively disabling the module on all projects on which it was enabled under the alternate prefix).

**Comment by mmcev106** [comment]
We've since enabled checking to prevent modules from being enabled if another module is already defined with the same module class name & namespace.  Closing, since this is likely not relevant anymore.
