### ISSUE TITLE
Rethink 'enable' language

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#133]
There is always some ambiguity about what 'enabling' a module means.  What do you think about having different language for the process of adding a module to your server and turning it on for a project?

What someone says, "Is that EM enabled" what are they thinking?  Are they asking if it is on your server?  Are they asking if it is active on their project (by virtue of some global hook)?  Just a thought for discussion.    I'd also like to understand what it means for an EM to be 'deactivated' due to an error.

Status:

"Discoverable",
    - Visible to End Users
 "Enabled",
    - Enabled at System
    - Enabled at Project
 "Configured"
    - Are there system-level settings in the external_module_settings?
    - Are there project-level settings?

Life Cycle - how do we visualize all of these different stages more easily?

- folder for em is present on server in one or more external-module folders
- folder for em is present on server AND has a valid config.json (can be parsed)
- em has been 'enabled' on system-wide level but perhaps never configured?  E.g. required fields could be missing?  Should a 'new' EM HAVE to be saved at least once in config if it has a config?
- em has been 'deactivated' on system-wide level due to a bug and presumably requires resolution.  
- em was 'enabled' on a system-wide level but is currently 'disabled' but has saved settings.  This is different from just being a folder on your computer as re-enabling it could make it behave differently than if it were new...  Should there be a warning about re-enabling something?
- em is 'enabled' for a specific project but not yet configured
- em is enabled and configured for a project
- em is disabled for a project (but has saved settings)
- em has never been enabled for a project (no settings) but is available to be enabled

many many more...    Just food for thought.

**Comment by 123andy** [comment]
If we are dreaming about changes - I think redoing the display and sorting of EMs would be high on my list.  I think a datatable with filters on top that shows all the various kinds of EMs (on the REPO, locally, enabled, disabled, etc...)  Then having a 'log' underneath that shows critical EM-related log activity such as when enabled, when disabled, when it threw an error, when configs were updated, etc...

**Comment by dr01d3r** [comment]
I'm a fan of all of that.  There are a good handful of things there that wouldnt be to difficult to implement, while providing a lot of value, especially to those that use a decent amount of modules or modules enabled in many projects.

**Comment by mmcev106** [comment]
Re-thinking error handling is on our TODO list, and could definitely end up being part of an activity log.  The other things you mentioned are NOT on our radar.  I'd be curious hear more about why/how they would be more helpful that what we have currently.

**Comment by mmcev106** [comment]
Closing since this hasn't been updating in over a year.  Feel free to reopen.
