### ISSUE TITLE
Module auto-downloading sometimes gets into a delete/download loop

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#136]
The following log shows a period of several weeks where I believe the date calc module existed on one web node and not the other (we have two here at Vandy).  It appears that the latter node kept trying to auto-download the module but must have been failing based on the number of repeat attempts spanning three versions of the module.

[datecalculatedfields download loop.txt](https://github.com/vanderbilt/redcap-external-modules/files/2586601/datecalculatedfields.download.loop.txt)

This was likely the cause of problems for the ARC project where this module was reported as working intermittently and sometimes not listed in the module list on the project.

We should be able to improve error detection to at least notify us if this issue occurs, it not resolve it.

**Comment by mmcev106** [comment]
I just updated the DAG Switcher module from 1.1.1 to 1.1.2, then just a few seconds later the the 1.1.2 directory was missing from both nodes (effectively disabling the module even though it was still marked as enabled).  Here are the relevant log entries:

```
mysql> select log_event_id, ts, description from redcap_log_event where log_event_id > 127296130 and (description like 'Download external module "dag%' or description like 'Delete external module "dag%' or description like 'Enable external module "dag%') order by log_event_id;
+--------------+----------------+----------------------------------------------------------------+
| log_event_id | ts             | description                                                    |
+--------------+----------------+----------------------------------------------------------------+
|    127296195 | 20181203170016 | Enable external module "dag_switcher_v1.1.2" for system        |
|    127296196 | 20181203170016 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296197 | 20181203170017 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296198 | 20181203170017 | Delete external module "dag_switcher_v1.1.2" from system       |
|    127296199 | 20181203170017 | Delete external module "dag_switcher_v1.1.2" from system       |
|    127296477 | 20181203170441 | Enable external module "dag_switcher_v1.1.1" for system        |
|    127296535 | 20181203170547 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296546 | 20181203170555 | Enable external module "dag_switcher_v1.1.2" for system        |
|    127296547 | 20181203170556 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296548 | 20181203170556 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296549 | 20181203170556 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296550 | 20181203170557 | Download external module "dag_switcher_v1.1.2" from repository |
|    127296551 | 20181203170557 | Delete external module "dag_switcher_v1.1.2" from system       |
+--------------+----------------+----------------------------------------------------------------+
```

I am adding this task to the "High Priority" milestone, since this can happen on a simple update.

**Comment by mmcev106** [comment]
Here's another example:

```
mysql> select
    -> log_event_id,
    -> ts,
    -> description
    -> from
    -> redcap_log_event
    -> where
    -> log_event_id >= (select log_event_id from redcap_log_event where ts >= 20181218000000 order by ts asc limit 1)
    -> and ( description like 'Download external module "survey%'
    -> or description like 'Delete external module "survey%'
    -> or description like 'Enable external module "survey%' )
    -> order by
    -> log_event_id;
+--------------+----------------+----------------------------------------------------------------------+
| log_event_id | ts             | description                                                          |
+--------------+----------------+----------------------------------------------------------------------+
|    129047991 | 20181218093634 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048020 | 20181218093635 | Enable external module "survey_link_lookup_v1.0.2" for system        |
|    129048034 | 20181218093637 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048036 | 20181218093637 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048038 | 20181218093637 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048039 | 20181218093638 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048042 | 20181218093638 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048043 | 20181218093638 | Delete external module "survey_link_lookup_v1.0.2" from system       |
|    129048044 | 20181218093637 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048046 | 20181218093637 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048048 | 20181218093638 | Delete external module "survey_link_lookup_v1.0.2" from system       |
|    129048050 | 20181218093637 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048051 | 20181218093638 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048053 | 20181218093639 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048055 | 20181218093638 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048056 | 20181218093638 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048057 | 20181218093638 | Delete external module "survey_link_lookup_v1.0.2" from system       |
|    129048058 | 20181218093639 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048062 | 20181218093639 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048063 | 20181218093639 | Delete external module "survey_link_lookup_v1.0.2" from system       |
|    129048064 | 20181218093640 | Delete external module "survey_link_lookup_v1.0.2" from system       |
|    129048065 | 20181218093639 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048066 | 20181218093640 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048067 | 20181218093640 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048068 | 20181218093640 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048069 | 20181218093640 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048070 | 20181218093640 | Download external module "survey_link_lookup_v1.0.2" from repository |
|    129048071 | 20181218093640 | Download external module "survey_link_lookup_v1.0.2" from repository |
+--------------+----------------+----------------------------------------------------------------------+
28 rows in set (0.00 sec)
```

**Comment by mmcev106** [comment]
I think I have a good solution.  @kcmcg and @taylorr4, would you mind reviewing the following commits?

8f5496f6738f98d368eb581224804e6929021f5a addresses # 1 above
36b3d6f3752b0a4d7ca0d319af924442e396190f addresses #'s 2&3 above

**Comment by mmcev106** [comment]
I was never able to reproduce this issue, but I'm fairly confident it was occurring when a module was updated during high traffic time and several threads were downloading/deleting the module directory faster than the download could finish (causing an infinite download/delete loop).  Commit 36b3d6f3752b0a4d7ca0d319af924442e396190f uses a temp directory as a lock file to prevent this scenario.

**Comment by kcmcg** [comment]
> I think I have a good solution. @kcmcg and @taylorr4, would you mind reviewing the following commits?
> 
> [8f5496f](https://github.com/vanderbilt/redcap-external-modules/commit/8f5496f6738f98d368eb581224804e6929021f5a) addresses # 1 above
> [36b3d6f](https://github.com/vanderbilt/redcap-external-modules/commit/36b3d6f3752b0a4d7ca0d319af924442e396190f) addresses #'s 2&3 above

The only questions I had was whether that redcap_log_event lookup runs fast enough on production data as I can see it potentially bogging down and whether 3 and 15 seconds really was a long enough timeout on the throttling.

**Comment by mmcev106** [comment]
Very good questions.

The download & delete methods should not be called very often at all.  Download should only be triggered by users accessing projects using the module on one of the nodes, and only until the module download finishes.  Delete is only ever triggered when an admin clicks the "Delete Module" button.  Also, our indexes seem to work very well on the throttling query.  It's normally limited to a few seconds, but if I edit the query to go back 10 years it still only takes 0.01 seconds:
```
select count(*) as count
from redcap_log_event l
where description = 'Download external module \"some_module_v1.0\" from repository'
and ts >= 20080000000000
```

I believe the timeframes are appropriate, but I'd love for someone else to think through them to check me.  I don't think we can expand them too much or it will be possible to trigger throttling by simply downloading, deleting, then downloading a module quickly through the control center.  When the download/delete loops in the logs above were occurring we were getting several download/delete requests per second.

**Comment by taylorr4** [comment]
That query is actually faster than i would expect. I wonder if it will be as fast for others. But regardless, it appears the query will not be looking farther back than 15 seconds, so i think it should always be pretty fast. And since this query is not going to be called very often at all, it makes it even less big of a worry for me. And even if you pushed the timeframe back to 10 minutes or so, i still wouldn't be too worried. But as you mentioned @mmcev106, many of these incidents were running several times a second, so it might not be necessary to look back more than a minute at most, i think.

**Comment by kcmcg** [comment]
Ok, sounds good. I guess if we somehow still end up triggering issues, we can tweak the throttling timeout then, but this makes sense for now. And now we'll have a log of how often these download/delete requests get triggered if an issue ever crops up again. Thanks for looking into this issue.
