### ISSUE TITLE
Worry that shazam not working under adding new records

### ISSUE THREAD

**Issue by navah93** [vanderbilt/redcap-external-modules#138]
Hello, 
I want to use shazam for few projects, but its working only via public survey and not under adding records which is out primary use. How can it be? how to fix this?

Thank you!

**Comment by 123andy** [comment]
Can you confirm you have the latest version installed as an external module?

**Comment by mmcev106** [comment]
@navah93, just FYI, this GitHub page is for the External Module Framework.  Issues for Shazam should be reported on [Shazam's GitHub page](https://github.com/susom/redcap-em-shazam).   Feel free to finish this discussion here if you like though.

**Comment by 123andy** [comment]
Sorry @mmcev106  -  I didn't notice that this was on the EM site.
@navah93 - see https://github.com/susom/redcap-em-shazam/issues/18
