### ISSUE TITLE
Would it make sense to add a more modern DB access layer to the EM framework?

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#146]
I'm envisioning something like [Medoo](https://github.com/catfan/Medoo), or even vanilla PDO.  We'd need to be careful about DB connection management (ideally we'd piggyback off the existing connection).  [Doctrine](https://github.com/doctrine/doctrine2) would be awesome, but it might be too opinionated to play nicely.

**Comment by 123andy** [comment]
I would love to document the use of prepared statements better and they should be used across REDCap - not just for EMs.  I was playing around with the db_xxx methods that @taylorr4 wrote and trying to use a prepared statement (which I think used PDO) but eventually gave up and moved to a sprintf "prepared" string instead.

**Comment by mmcev106** [comment]
Prepared statements are being implemented in [framework version 4](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/framework/v4.md).  We did consider other DB access layer options, but what we came up with for prepared statements seemed to be the best fit.  Closing...
