### ISSUE TITLE
Is requiring permissions for each hook in config.json helpful?

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#147]
This feature was originally intended to allow admins to review what a module would be doing before enabling it (like reviewing app permissions on a phone).  However, I'm not sure how helpful it actually is in practice.  We could remove the requirement for permissions, assuming there wouldn't be any issues (like a performance hit) from switching to **method_exists()** instead for triggering hooks

**Comment by 123andy** [comment]
I don't think it adds much value given that there is a 'pre-review' step before release to the repo.  We could instead have an optional 'activation disclaimer' tag in the config json that would display the text in the tag and add an 'i understand' checkbox.

An example might be an EM that does some sort of tracking and reports utilization to a third party address.  By offering a disclaimer, this absolves Vandy from having to 'determine' what is permissible and what isn't.  It creates a wider set of allowing functionality provided the end-user understands the implications.

Another example could be a module that writes to the database in an unsupported way.  During the review process you could offer feedback to the developer to add something to the disclaimer prior to approval...

Maybe?
```json
"disclaimers": [
  {
     "type": "system",
     "text": "This module does A",
     "require-approval": true
   },
   {
      "type": "project",
      "text": "Before you can use this on your project, you must send $10000000 to this paypal account :-)",
       "require-approval": false
    }
]
```
or perhaps break out into project-enable-disclaimer and system-enable-disclaimer and make it only a single block:
```json
"system-enable-disclaimer": 
  {
     "text": "This module does A",
     "require-approval": true
   },
"project-enable-disclaimer":
   {
      "text": "Before you can use this on your project, you must send $10000000 to this paypal account :-)",
       "require-approval": false
    }
```

**Comment by mmcev106** [comment]
Thanks for the input @123andy.  A disclaimer configuration seems more useful to me too.  If that existed today, would you add disclaimers to any of your current modules?

**Comment by 123andy** [comment]
In Shazam we have some fancy logic around how javascript is handled to prevent end-users from modifying anything with JS.

We also have some internal EMs that do things like mass-delete a bunch of records.  That might be another candidate if it were ever to be released externally...

All that said, it might just be a CYA sort of thing...

-A


—
Andrew Martin, PhD
Stanford University School of Medicine

On Nov 28, 2018, at 2:10 PM, Mark McEver <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the input @123andy<https://github.com/123andy>. A disclaimer configuration seems more useful to me too. If that existed today, would you add disclaimers to any of your current modules?

**Comment by mmcev106** [comment]
I'm going to close this for now since there's no real incentive to change it.
