### ISSUE TITLE
Should we consider automatically SQL-escaping all module GET/POST parameters for module pages?

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#148]
WordPress does this and it is generally a non-issue.  It does mean plugin/theme developers might have to unescape parameters that contain [escaped characters](https://stackoverflow.com/questions/6327679/what-does-mysql-real-escape-string-really-do) in some circumstances.  This effectively makes escaping inputs an opt-out task instead of opt-in, significantly reducing the chances of SQL-injection vulnerabilities.

@taylorr4 and @mcguffk, what are your thoughts?  If we might ever want to do this, it will be much easier to implement sooner than later.  I would want to review all existing modules to see what effects this might have, then give authors the chance to preemptively add support for it.

**Comment by taylorr4** [comment]
@mmcev106 i think this is probably for the best security-wise and makes sense to me. If we do this, we should probably include some kind of REDCap method or EM method for unescaping parameters, right?

**Comment by mmcev106** [comment]
We could definitely include an unescaping method.

**Comment by mmcev106** [comment]
I wonder if we should start versioning the AbstractExternalModule class or something so we can let module authors opt-in to potentially breaking changes like this on their on schedule.  That might help with #117 as well.

**Comment by mmcev106** [comment]
It looks like we'll be added parameterized queries soon.  After that, I wonder if the biggest risk with GET/POST params might be file path injection.

**Comment by mmcev106** [comment]
Parameterized queries are now in use by the framework itself, and are soon to be made available for  module code.  That feature worked out very well, and is a more comprehensive solution to this problem anyway.  Also, the `getSafePath()` method has been added for file path injection protection.  I'm going to go ahead and close this.
