### ISSUE TITLE
Streamline the process of updating many modules at once 

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#151]
In [this post](https://community.projectredcap.org/questions/36559/upgrading-external-modules.html?childToView=54562#answer-54562) Sean Banks said the following:

> Consider this workflow... a few weeks have gone by and REDCap tells me we have 12 modules that require upgrading. We currently have 31 modules installed. Ok... here we go. I click Upgrade. Then click Download. Then click Close. Then all of my available modules comes up. I find the module in the long list and click "Change Version". Then the module requests permissions. I click enable. Woo hoo! One upgraded. Check. Now I repeat for the second module. I click Upgrade. Then Download. Then Close. Then the available modules comes up. Now, I know I just clicked download like 10 seconds ago, but this time I can't even remember what module I was trying to upgrade. I just see a list of all 31 modules and it says "Change Version". So I need to look through and compare what modules have higher versions than what's listed in the current version. Ok. Figured it out. Change version... enable permissions. etc.
>
>I think you get my point. I know we're not at the point where we can just say "Upgrade automatically" like in the App store. That's ok. But I feel like there are definitely ways to make this run more smoothly, especially when thinking about the long term as we are managing more and more EMs on our instances.

**Comment by eaneuhaus** [comment]
See #115 for a similar discussion.

**Comment by mmcev106** [comment]
Rob has since added an "Update All" button.  Closing...
