### ISSUE TITLE
Page redirection issue (medium security level)

### ISSUE THREAD

**Issue by taylorr4** [vanderbilt/redcap-external-modules#169]
If you log into a plugin page for a module and then replace the "page" parameter with any URL, it will redirect the user to that URL. Example: https://redcap.vanderbilt.edu/external_modules/?prefix=mysql_simple_admin&page=https://amazon.com . Some sites are considering this a security issue by pen testers since authenticated REDCap users might be fooled into leaving REDCap and being sent to a possibly malicious site unwittingly. Can you please look into preventing this redirection if the page param is a URL? Thanks!

**Comment by mmcev106** [comment]
This redirection has been removed via commit 9fc3f2a.

In case it's helpful for future reference, this was added in the early days in commit f90f883.  I talked to Scott and I don't think we're using it at Vanderbilt anymore.
