### ISSUE TITLE
order and dependency

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#18]
Could an external module ever have a dependency on another external module?  Could someone make a great class for doing something then other modules use this class.

Should each module be self-contained and re-package all of this?  Or, should it be possible for a module to somehow access a class from another module?  If so, then how do we control module execution order such that the required class is available before the dependent module is run...

Sounds like the easy answer is just self-contained, but wanted to bring up the topic...

**Comment by mmcev106** [comment]
I have thought about this scenario a bit.  If/when I personally encounter a need to share code between modules (and that does not belong in the External Modules core code), I was planning on creating a plain old composer library hosted via git, and requiring it in each module.  We're already using a handful of composer dependencies.  I think it would be largely reinventing the wheel to use anything other than composer for dependency management, and I think it makes sense for shared code to exist as a library rather than a full-fledged module anyway.

Many WordPress plugins use composer in the same way we do now, and that system seems to work well enough (even though libraries are often duplicated between modules).
 There has been discussion for years in the WordPress community about adding dependency management for plugins, or a shared composer vendor directory (instead of each plugin having it's own), but nothing has materialized.

**Comment by tbembersimeao** [comment]
Regarding the execution order, we could add an additional column called `weight` to the `redcap_external_modules` table. The "heavier" the module, the later it is executed. This is how Drupal handles that.

**Comment by scottjpearson** [comment]
We talked about a few options here originally. Rightly or wrongly, we decided on a static function to be called by an External Module under a condition.
     ExternalModules::delayModuleExecution();
This function puts the current external module at the back of the processing queue/line.

The use cases we thought of involved waiting for data to come in. So it’d look like this:
if ($data[$record][$field] == “”) {
   ExternalModules::delayModuleExecution();
}

Eventually, it’ll “go" so as to prevent an infinite loop.

Again, the main thing we could think of that would delay execution was data flow. Thus, this setup made more sense than a priority scheme – as attractive as that is.

I hope this helps.

Scott J. Pearson
REDCap Data Core Programmer
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by tbembersimeao** [comment]
That makes sense. Thank you!

**Comment by tbembersimeao** [comment]
Regarding third-party dependencies, here is an idea of a "shared composer vendor directory" approach.

We could create a `composer.json` under `external_modules` directory that looks for other `composer.json` files included in the modules. Something like that:

```json
{
    "require": {
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "extra": {
        "merge-plugin": {
            "include": [
                "../modules/*/composer.json"
            ]
        }
    }
}
```

With a centralized `vendor` directory, REDCap Modules will be able to autoload all required libraries at once.

**Comment by tbembersimeao** [comment]
@mmcev106 Taking the _library_ dependencies apart, we could create a `config.json` setting called `dependencies` which lists modules prefixes (and its versions).

Based on that, modules having missing dependencies cannot be enabled on UI, until all dependencies are satisfied. In the same way, a given module that is required by other ones cannot be disabled on UI, until all its dependees are disabled as well.

Of course, we would need to display all the dependencies to the user.

Drupal adopts this approach for module dependency (although composer is used for everything else). Here is an example:
![drupal_dependencies](https://user-images.githubusercontent.com/29384017/36432579-89217508-1628-11e8-94d7-6926d95c61c7.png)

**Comment by mmcev106** [comment]
Drupal is a great example of centrally managed plugin/module dependencies working quite well.  I'd have to invest some time in carefully weighing all the factors before I'd have a strong opinion on whether that would work well for us.  The only downside I can think of is that you couldn't use different versions of a dependency on different projects without adding a lot of complexity.   It is possible to do that currently with composer,  as long as you don't have two modules with a dependency conflict enabled on the same project.

**Comment by mmcev106** [comment]
In practice, the `delayModuleExecution()` method that @scottjpearson and @knil-maloon implemented has worked quite well.  At the moment it does not seem likely that we have the resources to implement and maintain something more complex.  Closing for now...
