### ISSUE TITLE
On Control Center > External Modules, the ExternalModules object that hosts modules' JavascriptModuleObjects gets overwritten

### ISSUE THREAD

**Issue by grezniczek** [vanderbilt/redcap-external-modules#206]
As stated in the title, when browsing to _Control Center > External Modules_, the `ExternalModules` object that hosts modules' _JavascriptModuleObjects_ gets overwritten by the ExternalModules object defined in `manager/js/globals.js`. 

This, of course, breaks any EMs that rely on using their objects at a later point, e.g. in the `document.ready()` function.

Note, the modules' objects are created ok initially, but their hosting `ExternalModules` object is later replaced by a new instance. So either `globals.js` needs to be executed before any EM code is run, or care must be taken to not replace an existing object, but to merge into it instead. 

A third option might be to rename either the object holding EM Control Center info (i.e. the one in globals.js) or the object holding EM JavascriptModuleObjects. However, the names are hardcoded in several places in the EM framework code (and not easily found ... a lot of "ExternalModules" with different meanings around everywhere).

**Comment by mmcev106** [comment]
Thanks very much for reporting this!  I believe this commit should solve it:
https://github.com/vanderbilt/redcap-external-modules/commit/ffb0f7dc01c1fea4ecb8e57f25c74d01e98f02b1

Please feel free to reopen this if you have any more concerns here.
