### ISSUE TITLE
Should module settings be deleted when projects are deleted?

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#208]
I believe a cron job removes project metadata (like fields) from the database a month after the project is marked as deleted in the UI.  We should run this plan by @taylorr4, but we should likely modify this cron job to delete module settings as well, including edocs.  This should likely be implemented in a method in the module framework's `ExternalModules` class, with a single line call to it from the cron job in REDCap core.

Thanks to @scottjpearson for reporting this!

**Comment by taylorr4** [comment]
@mmcev106, module settings get deleted automatically when a project is deleted (i.e., after the 30 day period in the "recycle bin"). This is done via the project_id foreign key in redcap_external_module_settings, which deletes it from the table cascading from when the project is deleted from redcap_projects.

**Comment by mmcev106** [comment]
Awesome.  Thanks @taylorr4!
