### ISSUE TITLE
cron validation

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#209]
https://github.com/vanderbilt/redcap-external-modules/blob/de0913996433e8c93149987ea5d6c60df3f066e4/classes/ExternalModules.php#L3408

@scottjpearson  -  why the is_array() here instead of a simple is_numeric?

Also, a few lines lower, you check if hour is empty when you've already checked that it is numeric.

**Comment by scottjpearson** [comment]
Fixed in testing branch.
