### ISSUE TITLE
Ideas from Conference Discussions

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#21]
Questions from the conference - things to be discussed/worked out

**Q: How to make a custom configuration page for a module**
One solution is to use a custom javascript parameter to redirect the configuration page to a custom php configuration page

**Q: What about building an optional 'validation' method for the EM.**  The idea would be to verify that the module is configured properly or can check for dependencies, record-level issues, etc...  Perhaps the outcome of the validation could be stored as color/icon next to the enabled module.   The results of the validation could be an object like:

````json
    {
        "result":"pass|warning|fail",
        "message": "Your project is missing blah blah blah",
        "buttons": [ {
            "Fix": "validation_fix.php"
        }]
    }
````

**Q: What about controlling setting editing permissions.**
For example:
- for each parameter in the config.json, you could optionally add some sort of "project-privs" key.  The default being edit, but we could have "read only" and "hidden" - so that only super-users could edit or see some project-level permissions.

Also, how do you prevent a user from disabling a global module for their project if you don't want them to.

**Q: More Permissions** - people want to have a new permission for EM - and not assume that all design users should have EM rights.

**Q: What about visibility permissions for links.**  It is common that people want to have control over what links are visible on a redcap project page.  While one could write a hook to hide links, etc, perhaps an optional link config parameter can be made to control visibility (or, at a minimum add a class to the link so it can be easily hidden with JS/CSS).

**Q: Power-User setting:**  Down the road we may want to grant some 'power users' the ability to enable modules to their projects without super-user approval (much like the new API options)

**Q: Make the 'permissions' confirmation more clear** - distinguish which permissions are hooks being used and which are more 'reviewer flags' like deletes data...

(and more...)

**Comment by mmcev106** [comment]
Those all sound like very worthwhile changes.  Thank you for documenting them!  I suspect @taylorr4 will have to be the one to consider implementing most of them, but I will definitely keep them in mind in case there is any overlap with needs from our team.

**Comment by biggeeves** [comment]
**Deleting Modules**

If a module does not pass a security scan and the offending code must be completely removed from the server it may be necessary for an administrator to delete all the files in the external module. While this could be done by hand by someone with direct access to the server it would be better handled within REDCap. 

Modules can be disabled, but having vulnerable code remain on the server is problematic.

**Comment by mmcev106** [comment]
This feedback is a bit dated at this point.  Closing...  Feel free to re-open this or separate tickets if anyone has an up-to-date perspective on the above.
