### ISSUE TITLE
Replace all instances of @vanderbilt.edu in the code

### ISSUE THREAD

**Issue by taylorr4** [vanderbilt/redcap-external-modules#215]
For the transition in Dec 2019, i noticed that there are several @vanderbilt.edu emails listed in the framework that should be changed to @vumc.org.

**Comment by mmcev106** [comment]
Yep, I've been holding off on changing them since we were looking into changing way emails work in general.  It sounds like that's not going to happen anytime soon, so I'll go ahead and update them.

**Comment by mmcev106** [comment]
Done!
