### ISSUE TITLE
Should we have a .gitattributes file

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#222]
I'm just learning about all this, but I had a question:

How can I look through all the commits and find when a function was last modified?
I found that by adding a `.gitattributes` file that contained:
```
*.php .    diff=php
```
I could then run:
```
git log -L :downloadModule:classes/ExternalModules.php
```
and see all the commits that effected the downloadModule function inside of the ExternalModules.php class.  Pretty cool, eh?

There is probably another way of doing this - with my global .gitconfig or something, but thought I'd ask/share.

**Comment by mmcev106** [comment]
Wow, that is quite slick...  I recently switched from PHPStorm to VS Code as an experiment and method history was one of the few things I was missing.  I just made a global `.gitattributes` per [this page](https://stackoverflow.com/questions/28026767/where-should-i-place-my-global-gitattributes-file) using your example and it worked like a charm.  Thanks very much for sharing!  I guess I'll go ahead and close this issue, but feel free to reopen it if you want to continue discussing.
