### ISSUE TITLE
Current testing branch seems to be unable to get any system-level settings from the database

### ISSUE THREAD

**Issue by grezniczek** [vanderbilt/redcap-external-modules#224]
I couldn't really find the cause for it, but it seems that the way mysqli statements are prepared, they don't handle `project_id = null` correctly. The resulting query should be something like `ISNULL(project_id)` instead of `project_id in ("NULL")`.

This affects `getSetting()` in a system context (where project_id is null).

This change must have occured fairly recently.

**Comment by mmcev106** [comment]
The latest commit should resolve this.  While trying to refactoring out the "NULL" string logic I and accidentally committed a broken partial set of changes.  I just reverted it and will make sure the changes is working before I try again.  Please forgive the inconvenience!
