### ISSUE TITLE
system plugin pages

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#228]
When we render a page in 'system' context in the control center for an EM (such as a super-user page), we do not get the EM links on the sidebar anymore.

```
require APP_PATH_DOCROOT . "ControlCenter/header.php";
```

this can be remedied by adding:
```
 ExternalModules::addResource(ExternalModules::getManagerJSDirectory().'control_center.js');
    require_once APP_PATH_DOCROOT . 'ControlCenter/footer.php';
``` 

at the footer...  Should we consider making some internal method to help with this?  Maybe something like:

```
$module->renderControlCenterHeader();
$module->renderControlCenterFooter();
```
?

**Comment by mmcev106** [comment]
Hmmm, for me the following old fashioned `APP_PATH_DOCROOT . /ControlCenter/...` header and footer requires seem to be working just fine on system level pages, including showing the module links in the sidebar.  I don't believe `control_center.js` relates to showing the sidebar links.  This issue did inspire me to implement 4af056, but that is only useful for pages defined in `config.json`.  There is a bug in the `testing` branch currently that another developer is working to fix, so if you test this again I'd recommend using either the `production` branch, or the version bundled with REDCap (the `release` branch).  Please let me know if I'm missing something.

**Comment by mmcev106** [comment]
I guess I'll close this since it hasn't been updated in a few months.  Feel free to reopen it.
