### ISSUE TITLE
 REDCap Messenger conflict

### ISSUE THREAD

**Issue by aandresalvarez** [vanderbilt/redcap-external-modules#23]
When you are in a project, if you have the REDCap Messenger open the config option for the external module does not work correctly and lock the window. 
Here an example:
https://www.useloom.com/share/89331d8f27684caf980b1b8d6fe4f125

Maybe it is a problem with REDCap Messenger, and not with external modules.. Just for you to know..

All the best,

**Comment by mmcev106** [comment]
Thank you for reporting this.  I'll make sure it's on our TODO list.

**Comment by mmcev106** [comment]
This was fixed in REDCap core via this commit:

https://github.com/vanderbilt/REDCap/commit/726a1cc4dd88bf90ebe532d23ce3fa023355cd9d
