### ISSUE TITLE
version redirect for EM URLs

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#236]
I think we have an issue where the 'redirect' to the latest version of REDCap doesn't work for External Module urls.

In this example, the current server is 9.5.1 but the url was bookmarked as 9.3.5

So, if someone has:
https://you.edu/redcap_v9.3.5/ExternalModules/?...

The redirect tries to do so with an include of the  9.5.1 External modules but since the class has already been loaded from the original old version page hit, this results in an error (redeclaring the same object).

I think the answer is probably to have the source code do a redirect to the current EM version if there is an older version detected in an EM url but I haven't had the time to look deeply.   I think the code is in the actual REDCap bootstrap and not EM framework... (@taylorr4 )

**Comment by grezniczek** [comment]
I cannot see this behavior. Trying with the MySQL Simple Admin, calling a 9.3.5-versioned link to the plugin page in a 9.5.1 REDCap, this works as expected. The switch to the proper version is made with the call to `ExternalModules::callRedcapConnect();` (which calls the unversioned redcap_connect.php) in ExternalModules.php. 
While both version (from the link and current) of ExternalModules and AbstractExternalModule classes are included, I don't see any re-declaration error (at least not on PHP7.3.3), and I could confirm that only the current versions of these are actually used by any subsequent code.
So the redeclaring error may be PHP version specific?

However, it might be a good idea to move the version detection to an earlier time point, before the EM classes are included.

```
$noAuth = isset($_GET['NOAUTH']);
if($noAuth){
    // This must be defined at the top before redcap_connect.php is required.
    define('NOAUTH', true);
}

if(!defined('APP_PATH_WEBROOT')){
    if(!defined('PLUGIN')){
        // Since a change to redcap_connect.php on 4/6/18, this is required to make sure REDCap is initialized for command line calls like cron jobs.
        define('PLUGIN', true);
    }
    $connectPath = dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . "redcap_connect.php";
    require_once $connectPath;
}
```
at the top of `ExternalModules/index.php` should work.

This would ensure that a minimal amount of "old" code is loaded/executed (in this case only the code shown above).

**Comment by grezniczek** [comment]
Hmm, this indeed appears to depend on the PHP version. On a production system with 7.0.33, I get blank pages when calling the MySQL Simple Admin module with an outdated version link. So I have to assume the error described by @123andy occured.

**Comment by mmcev106** [comment]
Thanks very much for the bug report & the details.  I was able to produce this in one of our PHP 7 test environments (but not my local, which is curious).  Regardless, a good solution might be to copy/move the require for `redcap_connect.php` to the top of `index.php`, so the redirect happens before the `ExternalModules` class is loaded.  I'd like some input on this before I make any changes since it may affect others more than Vanderbilt (we use the dev override `external_modules` dir, so our module URLs are not versioned).  What are your thoughts?

**Comment by mmcev106** [comment]
@grezniczek, I apologize it sounds like you first recommended pretty much the same thing.  I was thinking of a little different implementation, so I incorrectly assumed it was a different solution from a quick skim.

**Comment by mmcev106** [comment]
What do you both think of this implementation of that fix?

https://github.com/vanderbilt/redcap-external-modules/pull/237

**Comment by 123andy** [comment]
I’m can’t think of a downside off the top of my head…. I do recall a year or so ago we were talking about the authentication flow when boostrapping Ems, but that is a separate discussion…. I guess we just try and see what breaks 😊

-A

**Comment by grezniczek** [comment]
Looks fine to me. 

I guess that extra file (redcap_connect.php in the EM directory) can't be avoided if code duplication should be minimized.

**Comment by mmcev106** [comment]
I just merged the PR to the `testing` branch.  Our current test/merge schedule would put that in the first REDCap version of the new year (NOT the next LTS release).  I think that is prudent since this is a riskier change.  However, feel free to reopen this if you think it's worth discussing getting it into the coming LTS release.
