### ISSUE TITLE
Breaking change in EM query function

### ISSUE THREAD

**Issue by pbchase** [vanderbilt/redcap-external-modules#246]
@mmcev106, we got a report of a module breaking in RC 9.6.3 in a call to ExternalModule::query.  See https://github.com/ctsit/warn_users_of_pending_suspension/issues/19 

The error leads us to this line wherein the `query` function no longer allows the default value of `null` for `parameters`. 

https://github.com/vanderbilt/redcap-external-modules/blob/2b50b5348661163596d8d37e2b366ce11620438c/classes/ExternalModules.php#L2252

This feels like a breaking change to us. Can the test `$parameters === null` at line 2165 be removed? This feels like a Framework V4 requirement, but we are seeing on a Framework V1 module.

**Comment by mmcev106** [comment]
Calling methods on the `ExternalModules` class directly is **NOT** supported.  They can change at any time.  Modules should always use the `query()` method on the module instance (or framework class).  For example, `$module->query(...)` or `$module->framework->query(...)`.  Feel free to re-open if you have any questions.

**Comment by pbchase** [comment]
Thanks, @mmcev106. We'll address that.
