### ISSUE TITLE
Module translations are not available in certain circumstances.

### ISSUE THREAD

**Issue by grezniczek** [vanderbilt/redcap-external-modules#251]
When translatable strings in `config.json` are used before the respective module is instantiated, the language strings are missing as they have not yet been added to the global `$lang` repository and this results in the _"Language key 'abc' is not defined"_ message. For example, the name of module links (added to the left-side menu) are affected.

Pull request https://github.com/vanderbilt/redcap-external-modules/pull/248 fixes this.

**Comment by mmcev106** [comment]
PR #248 has been merged.  Thanks!
