### ISSUE TITLE
Consider an officially supported way for plugins to access module features

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#256]
We keep encountering scenarios where it is cost prohibitive to convert a plugin into a module, but we want to use module features in the plugin (settings, logging, various helper methods, etc.).  We've created a few ways to accomplish this, but I'm afraid they're poorly designed and brittle.  Should we come up with an official way to do this?  Some ideas include:

- Simply making some methods on the `ExternalModules` class officially supported when called from within plugins.
- Creating a `PluginUtility` object (or something similar) that provides methods to plugins (would discourage using other methods on the `ExternalModules` that aren't supported).
- Creating a general `PluginModule` object that any plugin could use at any time.
- Making it possible to define modules in plugin folders

**Comment by mmcev106** [comment]
Rob and I just spoke about this briefly.  He recommended against officially supporting referencing modules or module framework functionality from plugins for the consortium.  I am inclined to agree with him, and might consider plugins effectively deprecated in favor of modules going forward.  Currently, I don't think there's any reason to refactor the few cases where we blur the lines here at Vanderbilt, but there might need to at some point in the future as the module framework grows.

**Comment by dr01d3r** [comment]
Hi @mmcev106 ,

I agree with the decision to avoid making a bridge between plugins and modules; however, the word "deprecated" worries me a little.  I'm assuming you're only referring to plugins not being able to take advantage of new features implemented in the EM Framework, and that core classes like `REDCap` and `Project` will continue to be available to plugins/hooks for the foreseeable future?

**Comment by mmcev106** [comment]
I don't think there's any reason to officially deprecate plugins, but I do personally view them as "effectively deprecated".  I don't think I'd ever start a new project as a plugin since there is more collaboration and growth going on in the module framework.
