### ISSUE TITLE
Documentation unclear on use of REDCap core classes

### ISSUE THREAD

**Issue by ChemiKyle** [vanderbilt/redcap-external-modules#260]
The official documentation is a bit unclear on the appropriateness of using the `REDCap` class methods. The [first paragraph of the official documentation](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/official-documentation.md#external-module-framework---official-documentation) mentions that all '[m]odules can utilize any of the "REDCap" class methods (e.g., `\REDCap::getData`)'. Later in the same document developers are recommended to [not reference any other methods or files](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/official-documentation.md#available-developer-methods-in-external-modules).

Contextually, I assume the latter statement refers specifically to the methods and files within scope of this repository (e.g. the `ExternalModules` class). But a few words or a sentence to the effect of drawing a line would be helpful in clarifying specifically what is verboten.

**Comment by mmcev106** [comment]
I just attempted to clarify this.  How does it look now?  Feel free to recommend specific changes if it's still unclear.  Other perspectives on such things can be very valuable.

**Comment by ChemiKyle** [comment]
I think that clears up the ambiguity nicely with minimal extra wording.
