### ISSUE TITLE
PHP version check

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#27]
So, with the most recent release of REDCap - if you try to place an 'external_modules' folder in the redcap root and you're still a poor sob on php 5.3 in some environments, your redcap just dies and doesn't show anything.  In fact, there are no errors reported to PHP either.

I'm wondering if the system.php class should check the php version before it tries to include the ExternalModules class as it uses namespaces.  In any event, the release of EM's is a hard-stop on php 5.3 which has otherwise been just a warning to the configuration page...

**Comment by taylorr4** [comment]
Good call, @123andy. I've now added a check for this in REDCap so that it doesn't include External Modules unless on PHP 5.4+. https://github.com/vanderbilt/REDCap/commit/707e7ec2c6890a680fc65234bf9609f6b73b89ba
