### ISSUE TITLE
Config does not clear first block of optional repeating fields on save after clearing saved value

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#28]
If you have a repeating field that isn't required that has a value and want to remove that value the UI hides the input, but upon save and reload, the old value is still present in the config.  (hope that makes sense)

**Comment by mmcev106** [comment]
Thanks @123andy!  @mcguffk, would you prefer to look into this, or would you like me to?

**Comment by 123andy** [comment]
Ok - this has changed since updating... but there is still something to discus.

What if you want to have 0 to N optional parameters.  Currently, the repeatable field acts as 1 to N.  If you leave it blank, you get a NULL in the getSettings for that array member.  Is it worth revisiting?  Or, if you want to to 0-n should you just ignore the nulls in your code... that might be easier.

**Comment by mmcev106** [comment]
@mcguffk made some changes recently that likely fixed that first issue you were seeing.

I agree that it likely makes sense to support 0 to N options for repeatables that are not required.  In practice this has not been an issue for us (so probably not high on the priority list).  @mcguffk, do you know how difficult this would be to add with the new repeatables implementation?

**Comment by 123andy** [comment]
I think it would a UI rework in where to put the buttons, etc...  Ideally I would like to apply a little more styling to the ui for the config page...  Any plans to do this on your end or should I try and take a hack at it.  

Also, I'd like to propose that @mcguffk or @mmcev106 or someone from Vandy sit in on some weekly 1-hour long 'ext mod reviews' with the folks who are most likely to start using them.  It would be great to co-author a few things together and work on building a best practice template, etc...

Any thoughts?  I posted this on the community forum but I think Kyle has been to busy running from the Sauna to Lake and back again...  At least that is what I was trying to convince him happens with people in Michigan.

**Comment by mmcev106** [comment]
We have no plans to spice up the config UI at the moment, so feel free.  Thank you!

I'm planning to be on the call this Thurs along with Kyle, and am very curious to hear what everyone else is doing.

**Comment by 123andy** [comment]
It would be great to have you or Kyle walk through the ExternalModule class at some time to talk about all the methods so everyone understands the high-level 'scope' of what's there...  I also think that getting this group together is a good chance to work on the documentation collaboratively...

**Comment by mmcev106** [comment]
The ExternalModules class is only intended for internal use.  The AbstractExternalModule class is the one that is publicly supported, and all it's methods are documented on the [GitHub Page](https://github.com/vanderbilt/redcap-external-modules/).

**Comment by mmcev106** [comment]
I think I'm going to close this for now since no one has had further thoughts for the past couple of months.
