### ISSUE TITLE
The addAutoNumberedRecord() method may not be safe for concurrent requests

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#296]
It attempts to be threadsafe by inserting then deleting possible duplicates, but that might just moves the "critical section" to the delete, making it possible to delete all newly inserted record ids.

**Comment by 123andy** [comment]
I was looking through the code around simultaneous survey entries in response to a post to the community site and felt as though the caching and lookup was not very efficient.  I think some form of db-lock is the only safe way to secure the next record id.  Either by locking a table for update or using the get_lock feature of mysql...

To add to this, there are many who want to 'customize' the syntax for addAutoNumberedRecord - such as "P001", "P002", ....   This would be an idea place for a hook.

**Comment by mmcev106** [comment]
Are you envisioning something like a `redcap_get_next_auto_numbered_record_id()` hook?

**Comment by mmcev106** [comment]
Perhaps for now we should simply remove our custom implementation and call save data with the undocumented auto ID flag set to true.

**Comment by 123andy** [comment]
Sorry - when I replied above - but I mean to say that the built-in redcap code being used for public survey record generation has a problem.  There have been multiple consortium reports of scenarios where two people posting simultaneously from a public survey end up getting the same ID where poster-2 overwrites the data of poster-1.  In one case, a pdf of data was sent to poster-1 that contained poster-2's data.

The code is complex due to the record caching as well.  It would be great if you could look at the source code and see if you and @taylorr4 could come up with a more atomic new record generator.  I think the only way to do it properly is a mutex in the database.  Perhaps for each project/arm there would be a 'last_auto_record_id'.  When someone calls getNextId - it would do a select FOR UPDATE to lock the row.  It would then use the current value to seed and begin checking if the next ID exists in the database.  If it doesn't, then it writes the new value to the table and returns.

If 10 people submit a public survey at the same time, they will have to wait in queue until the table becomes available - all of which would be managed by the innodb engine.

I would also love to see a hook point for this so we could easily add our own 'custom' record formatting.  People have complex requirements based on DAG, ARM, etc...

**Comment by taylorr4** [comment]
@123andy i would say that in REDCap itself, the auto-numbering process is pretty atomic if you use Records::addNewRecordToCache(), which sets a record name as a unique key in a temporary table when doing record auto-numbering, so that gets you close to a database lock-type thing (the "cache" does not refer to the record list cache, which came much more recently). That is essentially what needs to be used inside addAutoNumberedRecord(), i think. Looking now at addAutoNumberedRecord(), i agree that it should not be used with a lot of concurrent requests. So @mmcev106, i would request that you should probably look into integrating that into the EM framework. Also, it's important to note that using getAutoId() is good for determining what the next record should be, but Records::addNewRecordToCache() should be used when you are actively saving the record. I can see how it's now super straightforward though.

**Comment by 123andy** [comment]
I dug into this a week or so ago when that user reported two public survey responders getting records mixed...    I'm not sure you had time to review my post:

https://community.projectredcap.org/questions/81104/survey-response-overwritten.html

I came to the conclusion that there were two possible errors with the addAutonumberedRecord:

- a database error (which could result in a record ID being accepted given how the errors were handled) - unlikely but possible
- just simultaneous entry as there was no database locking used

I stand by my suggestion that it should be 'absolutely atomic' - and not sort of - by using a database MUTEX.  In MySql the easiest way to do this given that everyone is used innodb support is row-level locking or using a named GETLOCK() command.

I know this isn't a big problem and may not necessitate the resources, but it is still a problem that does violate HIPAA in a big way, that is unless you have determined how the reported issue above came to be?

I think the mixing of the 'record cache' with the adding a new record has created a bit of a quagmire.  I think separating those out features so you can have true, atomic entry, with per-arm custom naming formats, would be a good extension to REDCap.

**Comment by taylorr4** [comment]
I'm not sure we can get absolutely atomic, but i'm considering options. I responded on that thread you mentioned above about some of the details, which i think some weren't quite right in the discussion. But i'm looking into this now to see how this can be improved.

**Comment by mmcev106** [comment]
Thanks to you both!

Rob, I'll plan to switch to using `addNewRecordToCache()` soon.  We switched module setting saves to MySQL's `GET_LOCK()` feature over a year to make them fully atomic.  It has worked very well so far.

**Comment by mmcev106** [comment]
Transactions are probably also an appropriate option to guarantee atomicity.  I think we didn't use them in modules only because they might be inside a transaction defined by module code...

**Comment by 123andy** [comment]
Hi @mmcev106  and @taylorr4 - just got off a zoom with Sheree who wants to use this module:
https://github.com/susom/redcap-em-public-survey-dag

What is does is create a unique EM url for each DAG in the project as a 'dag-specific' public survey url.  When hit, it creates a record in that dag and redirects the client to the record.  This is just the sort of project that is vulnerable to an autoNumber problem and I'm wondering how to best solve it.

In fact, when I look at ANY of our EMs that create new records, they are potentially vulnerable.  So, I'm proposing we add some new plugin/api method that 'reserves' a record_id and ensures it is unique.  I just made up some code (haven't tested it) but would ask that you review it quickly for issues so I might try it inside the scope of my EM for Sheree and then see what you think about supporting it as an official method.

The reason we can't use the existing addNewRecordToCache is that is also uses the getAutoId function...  It isn't really accurately named - it should be addNextAutoIdRecordToCache (or something like that :-)

```php
    /**
     * This is a function to reserve a record id and ensure it is unique.
     * If it returns true, it will 'hold' the reserved new record for 1 hour to be saved to the REDCap data
     * table.  If it is 'false' you must try a different record ID.
     * @param      $project_id
     * @param      $record
     * @param null $event_id
     * @param null $arm_id
     * @return bool
     * @throws Exception
     */
    public static function reserveRecord($project_id, $record, $event_id = null, $arm_id = null)
    {
        // SET $P AS CURRENT PROJECT
        global $Proj;
        /** @var \Project $P */
        $P = (empty($Proj) || $Proj->project_id !== $project_id) ? new \Project($Proj) : $Proj;
        
        // GET ARM_ID AND EVENT_ID IF NOT SUPPLIED
        if (empty($arm_id)) {
            if (empty($event_id)) {
                // Missing both event_id and arm_id -- assume first arm_id
                $arm_id = $P->firstArmId;
                $event_id = $P->firstEventId;
            } else {
                // We have an event_id, but not the arm.  Let's retrieve it
                foreach ($P->eventInfo as $p_event_id => $p_armDetail) {
                    if ($p_event_id == $event_id) {
                        $arm_id = $p_armDetail['arm_id'];
                        break;
                    }
                }
            }
        } else {
            // We have the arm
            if (empty($event_id)) {
                // Get event from arm
                $event_id = $P->getFirstEventIdArmId($arm_id);
            }
        }

        if (empty($event_id) || empty($arm_id) || empty($record)) {
            throw new exception ("Missing required inputs for reserveRecord");
        }
        
        
        // STEP 1: CHECK THE NEW_RECORD_CACHE FIRST FOR HIGH-HIT SCENARIOS
        // Is the record in the redcap_new_record_cache
        $sql = sprintf("select 1 from redcap_new_record_cache
            where project_id = %d and arm_id = %d and record = '%s'",
            intval($project_id),
            intval($arm_id),
            db_escape($record)
        );
        $q   = db_query($sql);
        if (!$q) {
            throw new Exception("Unable to query redcap_new_record_cache - check your database connectivity");
        }
        if (db_num_rows($q) > 0) {
            // Already used
            return false;
        }
        
        
        // STEP 2: SINCE THE NEW_RECORD_CACHE DOESNT INCLUDE OLDER RECORDS, LETS CHECK THERE TOO:
        // Is the record used in the record list or redcap_data
        $recordListCacheStatus = \Records::getRecordListCacheStatus($project_id);
        ## USE RECORD LIST CACHE (if completed) (requires ARM)
        if ($recordListCacheStatus == 'COMPLETE') {
            $sql = sprintf("select 1 from redcap_record_list
                where project_id = %d and record = '%s' limit 1",
                intval($project_id),
                db_escape($record)
            );
        }
        ## USE DATA TABLE
        else {
            $sql = sprintf("select 1 from redcap_data
                where project_id = %d and field_name = '%s'
                and record regexp '%s' limit 1",
                intval($project_id),
                db_escape($P->table_pk),
                db_escape($record)
            );
        }
        $q = db_query($sql);
        if (!$q) {
            throw new Exception("Unable to query redcap_data for $record in project $project_id - check your database connectivity and system logs");
        } else if (db_num_rows($q) > 0) {
            // Record is used
            return false;
        }

        // STEP 3: LETS TRY TO ADD IT TO THE NEW RECORD CACHE TO ENSURE IT IS STILL UNIQUE
        $sql = sprintf("insert into redcap_new_record_cache (project_id, event_id, arm_id, 'record', 'creation_time')
            values (%d, %d, %d, %s, %s)",
            intval($project_id),
            intval($event_id),
            intval($arm_id),
            db_escape($record),
            db_escape(NOW)
        );
        if (db_query($sql)) {
            // Success - record is reserved
            return true;
        } else {
            // Duplicate or other error
            // TODO: look at error code to differentiate from a lock error vs. another db error
            return false;
        }
    }
```
Thoughts?  Or, should we build a custom framework locking method?

------------

As an aside @taylorr4 , I still don't understand this line in the addNewRecordToCache?  It seems like a DB error could lead to assigning a record_id that isn't unique:
`if (!$q) return $record;`

**Comment by 123andy** [comment]
Fixed some typos and tested it.  appears to be working...

**Comment by 123andy** [comment]
Here are two examples using this new method for this external module:

```php
    /**
     * Like next ID but prefixes id with the DAG name (e.g. stanford-1) or DAG ID (e.g. 15-1)
     * @param $dag_id
     * @return string
     * @throws \Exception
     */
    function getNextDagId($dag_id) {
        // See what kind of prefix is configured (either text or dag_id)
        $use_id_instead = $this->getProjectSetting('use-dag-id-instead');
        $dag_name = ( $use_id_instead ? $dag_id : REDCap::getGroupNames(true,$dag_id) ) . "-";

        // Get the length of the dag prefix so we can increment the suffix
        $dag_len = strlen($dag_name);

        // Load current records to find the current max suffix
        $records = REDCap::getData('array', null, array(REDCap::getRecordIdField()));
        $next_suffix = 1;
        foreach ($records as $k => $v) {
            if( substr($k, 0, $dag_len) === $dag_name ) {
                $suffix = substr($k,$dag_len);
                if (is_numeric($suffix) && $suffix >= $next_suffix) {
                    $next_suffix = $suffix;
                }
            }
        }

        // Reserve the Next_ID
        $loop_count = 0;
        do {
            $next_suffix++;
            $next_id = $dag_name . $next_suffix;
            $result = self::reserveNewRecordId($this->getProjectId(), $next_id);
            if ($loop_count++ > 100) {
                throw new \Exception("Overrun in " . __METHOD__ . " - $loop_count failed attempts");
            }
        } while ($result === false);

        return $next_id;
    }


    /**
     * Get the next record id
     * @return int|string
     * @throws \Exception
     */
    function getNextId() {

        // Get current max ID
        $records = REDCap::getData('array', null, array(REDCap::getRecordIdField()));
        $next_id = 1;
        foreach ($records as $k => $v) {
            if (is_numeric($k) && $k >= $next_id) {
                $next_id = $k;
            }
        }

        // Reserve the next_id
        $loopCount = 0;
        do {
            $next_id++;
            $result = self::reserveNewRecordId($this->getProjectId(), $next_id);
            if ($loopCount++ > 100) {
                throw new \Exception("Overrun in " . __METHOD__ . " - $loopCount failed attempts");
            }
        } while ($result === false);

        return $next_id;
    }
```

**Comment by taylorr4** [comment]
@123andy i'll modify the `if (!$q) return $record;` code in the next version to deal with that. In the REDCap code internally, $q will never be false, but i'll add some things to make it less error prone in case a module calls that internal method without all the required params. 

If we want this new method to be more user-friendly, i would suggest it be like this: `reserveNewRecordId($project_id, $record, $arm_num)` with only 3 params, in which you only need to pass the arm NUMBER (instead of the arm ID and the event ID - i'm not 100% sure why event_id is really in that db table - i think i had other plans to use it originally but didn't go that route). I can confirm that event_id doesn't really need to be accurate so long as ANY event_id from the correct arm is added. Then with just the arm number inside the method, you can convert the arm NUMBER to its arm ID and then just use the first event_id of that arm (via `$P->getFirstEventIdArmId($arm_id)`). I think that would way more simplified for developers to use this.

Regarding your reserveNewRecordId() method, i've reviewed the code several times, and it is solid. @mmcev106, i think it would make a good addition to the EM Framework. Also, i'd still like to chat soon about modifying the addAutoNumberedRecord() method since i'm worried that in its current state it could cause some problems for projects. Let me know if you have time to chat about it this week.

**Comment by mmcev106** [comment]
@123andy, my current plan is to finish PR #303 and remove all record creation logic from the framework since it should be defined only in one place in REDCap core.  I'm not sure I fully understand the reasoning on creating `reserveNewRecordId()`  vs. just using `addNewRecordToCache()`, but that discussion might be outside the scope of the EM framework regardless.

**Comment by mmcev106** [comment]
@123andy, it looks like PR #303 might change to simply replace the entire `addAutoNumberedRecord()` implementation with a `saveData()` call.  I'm hoping to finish that later today.

**Comment by 123andy** [comment]
Thanks guys.  @taylorr4  -  I was just rereading the code and had the same question about the event_id column in the new_record_cache table...  From a developer's perspective, we always have the event_id and not the arm, so I like idea of a method accepting the event_id instead of the arm (or in addition to the arm) - that is why I coded it up with that helper function at the top so you could provide either one.

I have tested it and it seems to work.

@mmcev106 - the reason I propose a new function is that the current function assumes you are auto-incrementing a numeric id (i.e. 55,56,57,58...) and we have many EMs where people want to have custom record IDs, such as:  'P056', 'P057', ...  Or, in the case of this EM, there are options for prefixing the record_id with the DAG Name or the DAG ID.  

Two options:

1. We modify the existing `addNewRecordToCache()` in two ways:
   1. We remove the while loop that auto-increments the id in the event of a used record id and do that outside in a new function.
    1. We add an argument that forces the function to query the record_cache / redcap_data tables as well.  Currently the function only checks the new_record_cache table and assumes the code has already called getAutoId prior which opens up cases where the ID might be in the redcap_data but not the new_record_cache and you could get a false result thinking it is unique.

2. We rename the current addNewRecordToCache() to instead me 'addNewAutoIdRecordToCache()' and have a new method more like the one I wrote above...  I think the new record cache is cleared after 3 hours, not 1 hour as I had in the comments above...

I just took an attempt and fixing up the code I scribbled above.  There were a few minor errors.  The redcap_data check wasn't arm-specific... 

```php
class Record
{
    /**
     * DETERMINE IF A RECORD EXISTS
     * This method does NOT Guarantee that the record_id supplied is unique
     * and can be used - call the reserveRecordId method instead.
     *
     * @param       $project_id
     * @param       $record             Proposed record id
     * @param null  $event_id           Any event in the arm or defaults to first
     * @param null  $arm_num            Arm number (1, 2, ...)
     * @param bool  $useRecordListCache Use the cache table for record_id vs. query redcap_data
     * @return bool
     * @throws Exception
     */
    public static function recordExists($project_id, $record, $event_id = null, $arm_num = null, $useRecordListCache = true)
    {

        // SET $P AS CURRENT PROJECT
        global $Proj;
        /** @var \Project $P */
        $P = (empty($Proj) || $Proj->project_id !== $project_id) ? new \Project($Proj) : $Proj;

        // GET ARM_ID
        if (empty($arm_num)) {
            // Get arm_num from event_id or take first
            $arm_num = empty($event_id) ?  $P->firstArmNum : $P->eventInfo[$event_id]['arm_num'];
        }
        $arm_id = $P->getArmIdFromArmNum($arm_num);

        if (empty($arm_id) || empty($record)) {
            throw new \Exception ("Missing required arm_id or record missing");
        }


        // STEP 1: CHECK THE NEW_RECORD_CACHE FIRST FOR HIGH-HIT SCENARIOS
        $sql = sprintf("select 1 from redcap_new_record_cache
            where project_id = %d and arm_id = %d and record = '%s'",
            intval($project_id),
            intval($arm_id),
            db_escape($record)
        );
        $q   = db_query($sql);
        if (!$q) {
            throw new Exception("Unable to query redcap_new_record_cache - check your database connectivity");
        }
        if (db_num_rows($q) > 0) {
            // Already used
            return true;
        }


        // STEP 2: Check the record_list or redcap_data
        // since the new_record_cache doesn't include older records
        $recordListCacheStatus = \Records::getRecordListCacheStatus($project_id);
        ## USE RECORD LIST CACHE (if completed) (requires ARM)
        if ($useRecordListCache && $recordListCacheStatus == 'COMPLETE') {
            $sql = sprintf("select 1 from redcap_record_list
                where project_id = %d and arm_id = %d and record = '%s' limit 1",
                intval($project_id),
                intval($arm_id),
                db_escape($record)
            );
        } else {
            ## USE DATA TABLE (search within arm)
            $sql = sprintf("select 1 from redcap_data rd
                join redcap_events_metadata rem on rd.event_id = rem.event_id
                where rd.project_id = %d and rem.arm_id = %d
                and rd.record regexp '%s' and rd.field_name = '%s' limit 1",
                intval($project_id),
                intval($arm_id),
                db_escape($record),
                db_escape($P->table_pk)
            );
        }
        $q = db_query($sql);
        if (!$q) {
            throw new \Exception("Unable to query redcap_data for $record in project $project_id - check your database connectivity and system logs");
        }

        if (db_num_rows($q) > 0) {
            // Record is used
            return true;
        }

        // Record *probably* does not exist
        // (it could have been created as this method was running... use reserveNewRecordId to guarantee uniqueness)
        return false;
    }


    /**
     * Try to reserve and guarantee a unique record_id in the project/arm.
     * If this returns true, the record id will be 'held' the new_record_cache table for ~3 hours
     * You should write the record_id to redcap_data before that time to ensure it is still unique
     *
     * If the record is not saved before that time, it can be re-reserved in the future by another
     * process
     *
     * Event_id is optional.  If not supplied the first arm is assumed.
     * For multi-arm projects, you can provide any event_id from the intended record arm.  A record is only reserved
     * within its arm.  This will not guarantee the id is not used in other arms.
     *
     * @param      $project_id
     * @param      $record
     * @param null $event_id
     * @return bool
     * @throws \Exception
     */
    public static function reserveNewRecordId($project_id, $record, $event_id = null)
    {
        if (self::recordExists($project_id, $record, $event_id)) return false;

        // Get the arm_id from the event_id
        /** @var \Project $P */
        global $Proj;
        $P = (empty($Proj) || $Proj->project_id !== $project_id) ? new \Project($Proj) : $Proj;
        if (empty($event_id)) $event_id = $P->firstEventId;
        $arm_id = $P->eventInfo[$event_id]['arm_id'];

        // Attempt to insert into new_record_cache - if used by another process we will get a unique constraint violation
        $sql = sprintf("insert into redcap_new_record_cache
            (project_id, event_id, arm_id, record, creation_time)
            values (%d, %d, %d, '%s', '%s')",
            intval($project_id),
            intval($event_id),
            intval($arm_id),
            db_escape($record),
            db_escape(NOW)
        );
        if (db_query($sql)) {
            // Success
            return true;
        } else {
            // Duplicate or other error
            return false;
        }
    }
}
```

Also here:  https://gist.github.com/123andy/8f338af06ac82d7fd39609abcbab1b19

**Comment by mmcev106** [comment]
If we were to add this to the framework, I wonder if simply adding a `$prefix` argument to the existing `addAutoNumberedRecord()` method would provide the best interface.  If omitted, we could just call `saveData()` with the auto numbering flag set to true.  If a `$prefix` is specified, we could use @123andy's implementation and automatically save the record so the method behaves the same way in both contexts, and developers don't have to worry about reservation timeouts.

@taylorr4, do you think auto numbering prefixes is a common enough use case for the EM framework to commit to supporting it?  If so, how do you feel about this specific implementation?  It looks like it duplicates some of REDCap's internal auto ID logic, but perhaps that's OK in this context.

**Comment by 123andy** [comment]
I just updated the gist again (sorry)...  Adding a little more flexibility..  I think this code belongs in the core, not just EMs and should be made available as plugin methods off the REDCap::  class.

My changes are in version 2 of the gist

**Comment by 123andy** [comment]
Also, some EMs want padding, so:
P0001, P0002, ...  This can't be done with a simple prefix without knowledge of the whole thing.  I'm all for having a method to reserve and get the next record ID via an API call, or event pass a wildcard '*' for the record_id and have it automatically happen during save/import, but I think all the options should probably be available...

**Comment by taylorr4** [comment]
@123andy FYI i'll be renaming the method Records::addNewRecordToCache() to Records::addNewAutoIdRecordToCache() in the next release for clarity going forward. I'm not sure how comfortable i feel right now about changing the mechanics of the current auto-id generation in these methods with regard to trying to keep things stable under the current climate. 

I don't have as much time right now to dig in deep in these discussions (as much as i appreciate them), but i'm willing to review any PRs if you wish to add one with your ideas. That would give me time to review it and decide at what time we feel comfortable adding it into the base REDCap code, if it makes sense at the time. Thanks!

**Comment by 123andy** [comment]
ok - rob.  Once you make your change in the next version, I'll try to make a PR that doesn't change existing functionality but offers the plugin methods for us.  I may 'duplicate' some of the functionality that you have in that class, but if you then feel comfortable you could migrate to using it in a more compartmental fashion...

**Comment by mmcev106** [comment]
PR #306 makes `addAutoNumberedRecord()` safe for concurrent requests, and it sounds like the rest of this discussion will move to a PR against REDCap core.  Closing...
