### ISSUE TITLE
REDCap version forwarding of EM urls can break with updates to the ExternalModules class

### ISSUE THREAD

**Issue by grezniczek** [vanderbilt/redcap-external-modules#327]
This would then lead to crashes of REDCap, as described here:
https://community.projectredcap.org/questions/83749/are-external-module-links-redcap-version-specific.html

Reason being that a method that was called did not exist in the earliear version of the ExternalModule class that was loaded first (and apparently is relevant even when new versions are "required" on top of it).

The best way to fix this would be to have REDCap do it's forwarding **before** any EM stuff is touched.

If this isn't feasible, then a way to unload old class definitions would be needed (no idea of this is possible). 
Digging a bit on the net, I came accross this: https://www.sitepoint.com/community/t/unloading-a-class/18864
But I guess wrapping the EM-framework in a versioned namespace would break even more ...

**Comment by grezniczek** [comment]
There is [runkit_import](https://www.php.net/manual/en/function.runkit-import.php) ... but that's not really an option.

**Comment by grezniczek** [comment]
To quote from ExternalModules/index.php:
_We call redcap_connect.php before loading any classes to make sure redirections from previous REDCap version URLs happen first.  We don't want to try to load old and new versions of the same class._

Which was not present in 9.4.2 ... ah, so this has been recognized. 

**This means there is no fix for old versions. And it won't happen in newer ones. Closing this.**

**Comment by 123andy** [comment]
This comes from #236 I think...

**Comment by grezniczek** [comment]
Gee. I even took part in the discussion there (although not very gloriously it seems). Would not have remembered that. Thanks, @123andy ;)
