### ISSUE TITLE
framework->getSubSettings in constructor causes loop

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#329]
Hi guys,

The breaking change to 9.10 wrt getSubSettings() caused my SurveyUITweaks EM to crash.  I added a framework version to the module and was able to get it to work, but only after removing the
```
$this->framework->getSubSettings('foo')
```
from the constructor and instead calling it before each hook function.

So, this appears to cause a recursive loop:
```
    function __construct()
    {
        parent::__construct();
        if ($this->getProjectId()) {
            // Load the project settings
            $this->settings = $this->framework->getSubSettings('survey_tweaks');
        }
    }
```

Here is the output:

```

Call Stack
--
1 | 0.0207 | 388496 | {main}( ) | .../index.php:0
2 | 0.1053 | 935304 | include( '/var/www/html/redcap_v9.9.9/Surveys/index.php' ) | .../index.php:28
3 | 0.6369 | 14608424 | HtmlPage->PrintHeader( ??? ) | .../index.php:1957
4 | 0.6437 | 14609376 | Hooks::call( ???, ??? ) | .../HtmlPage.php:133
5 | 0.6438 | 14609376 | ExternalModules\ExternalModules::callHook( ???, ???, ??? ) | .../Hooks.php:42
6 | 0.7035 | 14632256 | ExternalModules\ExternalModules::ExternalModules\{closure:/var/www/html/redcap_v9.9.9/ExternalModules/classes/ExternalModules.php:2811-2823}( ???, ??? ) | .../ExternalModules.php:2826
7 | 0.7035 | 14632256 | ExternalModules\ExternalModules::startHook( ???, ???, ??? ) | .../ExternalModules.php:2812
8 | 0.7058 | 14632768 | ExternalModules\ExternalModules::getModuleInstance( ???, ??? ) | .../ExternalModules.php:2648
9 | 0.7058 | 14632768 | ExternalModules\ExternalModules::getFrameworkInstance( ???, ??? ) | .../ExternalModules.php:2997
10 | 0.7238 | 14731000 | Stanford\SurveyUITweaks\SurveyUITweaks->__construct( ) | .../ExternalModules.php:3056
11 | 0.7717 | 14789424 | Stanford\SurveyUITweaks\SurveyUITweaks->__get( ??? ) | .../SurveyUITweaks.php:34
12 | 0.7717 | 14789424 | ExternalModules\ExternalModules::getFrameworkInstance( ???, ??? ) | .../AbstractExternalModule.php:1236
13 | 0.7806 | 14794080 | Stanford\SurveyUITweaks\SurveyUITweaks->__construct( ) | .../ExternalModules.php:3056
14 | 0.8060 | 14798304 | Stanford\SurveyUITweaks\SurveyUITweaks->__get( ??? ) | .../SurveyUITweaks.php:34
15 | 0.8060 | 14798304 | ExternalModules\ExternalModules::getFrameworkInstance( ???, ??? ) | .../AbstractExternalModule.php:1236
16 | 0.8134 | 14802960 | Stanford\SurveyUITweaks\SurveyUITweaks->__construct( ) | .../ExternalModules.php:3056
17 | 0.8328 | 14807504 | Stanford\SurveyUITweaks\SurveyUITweaks->__get( ??? ) | .../SurveyUITweaks.php:34
```

In `getFrameworkInstance` it refers to `@self::$instanceCache` which appears to stay null as more and more copies of the EM are instantiated...

**Comment by mmcev106** [comment]
Thanks very much for the detective work @123andy.  I'll try to pinpoint this and find a way to prevent it tomorrow.

**Comment by mmcev106** [comment]
@123andy, I think I have a good fix in the works, and hope to send a PR your way soon.  Before I forget, I thought I should mention that caching project specific data in a module constructor is not a safe use case since the module instance is shared between all projects.

**Comment by grezniczek** [comment]
Yes, doing stuff in the constructor can bite you back! I had done this in the past, too, in a few of my modules only to get nasty stuff happening (sometimes), especially when it involved settings. I have since moved all such code out of constructors and call this init code at the entry points (i.e. hooks).

**Comment by 123andy** [comment]
@mmcev106 - if your EM only operates in a 'project context' then how is it bad to cache project-specific data in the constructor?  Can you give an example where this is problematic?

In this case, our EM is triggered off of more than one hook (every_page_top) and (survey_page) so by caching it in the constructor, we prevent having to call the getSettings methods twice.  Alternatively, could build an internal cache object and scope it by project_id but can't think of a use case where this would work.

The cases where I can think that we 'share' a project-level EM in a single php session are when using cron jobs - but since many of the REDCap methods are still bound to the pid in the url, I typically call out using http_get to start a new session for that specific project_id EM method...

**Comment by mmcev106** [comment]
Crons are probably the best example.  There may be others I'm not thinking of...  There is the project ID check preventing it from running on system pages though.  It might be fine...  Perhaps this has only bitten me in the past where a module started out in a project context, then a cron job or something was added later and it wasn't immediately apparent that other refactoring was required.

**Comment by mmcev106** [comment]
I've created [REDCap PR #303](https://github.com/vanderbilt/REDCap/pull/303) to get this fixed in the next release.  I'll go ahead and close this, but feel free to continue any discussion.
