### ISSUE TITLE
API hook / endpoint

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#42]
On the call with Jonathan re: myCap and the issue of the API hook/endpoint came up.  What are the current thoughts on this?  I have a few custom plugins that use pseudu-API tokens for authentication...   I would like to convert to EMs and just curious on thoughts thus far.

**Comment by taylorr4** [comment]
@123andy, i had already talked to @mmcev106 about this last week after speaking with @swaffoja about using the API endpoint as an alternative way to get a static/version-less URL that never changes, even with REDCap upgrades and module upgrades. The API and surveys endpoints were the only viable options without adding a whole new endpoint, so we went with hijacking the API endpoint. The end result of this can be seen in Pull Request https://github.com/vanderbilt/redcap-external-modules/pull/44.
