### ISSUE TITLE
select2.js and backspace key

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#46]
If I create a project-id dropdown in the config.js file, and start typing the name of a project, I can't use the backspace key to go back.
Also, for the project-id list, I think including the project id is worth while.  For those of us with hundreds of projects with our username on them, we often want to use auto-complete by project_id to find the correct project.  Maybe:

[123] Project A
[124] Project B
...

**Comment by tbembersimeao** [comment]
@123andy @mmcev106 the backspace problem is caused by the code below, located at `Resources/js/base.js`, in REDCap core.

``` php
// Disable the backspace-goes-back "feature" of browsers
$(document).on("keydown keypress", function(event) {
        // can't use ":input" because default behavior is to go back if
        // backspacing a radio button (at least in Chrome)
        if (event.which === 8 && !$(event.target).is(":text,:password,textarea")) {
                event.preventDefault();
        }
});
```

Select2 input field type is `search`, so appending it to the exceptions selector fixes the bug: `:text,:password,:search,textarea`.

**Comment by tbembersimeao** [comment]
Here is a PR that adds project IDs to project-id selection choices - https://github.com/vanderbilt/redcap-external-modules/pull/1

Bonus: the pull request also includes an "autocomplete" config that enables Select2 for a given dropdown element.

**Comment by mmcev106** [comment]
Much appreciated Tiago.  Thank you!

**Comment by tbembersimeao** [comment]
@taylorr4 is it possible to include `Resources/js/base.js` fix on next release? This backspace issue is becoming recurring in my team projects. It's a pretty simple fix.

**Comment by taylorr4** [comment]
@tbembersimeao, sure, no problem. Sounds good. Will include that fix in the next release. Thanks!

**Comment by tbembersimeao** [comment]
Thank you @taylorr4 !
