### ISSUE TITLE
Return value for empty project setting

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#56]
I suggest specifying what is returned when the setting is completely empty.

getProjectSetting($key&nbsp;[,&nbsp;$pid]) | Returns the value stored for the specified key for the current project if it exists.  If this setting key is not set (overriden) for the current project, the systemwide value for this key is returned.  In most cases the project id can be detected automatically, but it can optionaly be specified as the third parameter instead. _**If no value is set null is returned.**_

**Comment by mmcev106** [comment]
This [has been added](https://github.com/vanderbilt/redcap-external-modules/commit/8da3ab209b26e94a55bee569216fddb0e1424702)!
