### ISSUE TITLE
Truncated Var Labels

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#59]
When using the field type "field-list" the variable labels are correct but truncated. 
![truncated_var_labels](https://user-images.githubusercontent.com/3834165/32345198-b4f185a0-bfc6-11e7-859e-750c35d35cf4.gif)

Or possibly specify that the label will be truncated to first X characters.

**Comment by 123andy** [comment]
This is intentional to prevent really long labels...  Perhaps if it is truncated one could add a ... at the end.

**Comment by biggeeves** [comment]
This doesn't prevent long labels, it just cuts them off. 

_(I also use an old system where all labels must be 72 characters or less and all value labels must be less than 32 characters. I love the brevity and accuracy of short labels)_

**Comment by 123andy** [comment]
I didn't mean it 'prevents' the labels in redcap - it prevents the long labels from messing up the dropdown interface in the configuration page.  I think adding '...' is sufficient.

**Comment by taylorr4** [comment]
FYI, i went ahead and dealt with this issue in the following commit: https://github.com/vanderbilt/redcap-external-modules/commit/8f752cd1b937e97d52c42ffd92a88a147defcfbd

**Comment by mmcev106** [comment]
Thanks Rob!
