### ISSUE TITLE
Required project_id when in Control Center Enable Module

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#61]
Issue: Can not enable Module
History: Enabled a module, went to two projects and enable the module in each project. Then I used the Control Center "Disable Module" to globally disable the module.   The module was disabled.  Went to enable module again in Control Center _(not in project)_.  Error message is displayed: 

> Exception while enabling module: No project_id provided!
> This module requests the following permissions:

The line of code that is executing is below in this function indicated by asterisks: 

```
	public static function getData()
	{
		global $salt, $lang, $user_rights, $redcap_version, $edoc_storage_option,
			   $record_data_tmp_file, $record_data_tmp_filename, $record_data_tmp_line, $record_data_tmp_line_num;
		// Get function arguments
		$args = func_get_args();
		// Make sure we have a project_id
		**if (!is_numeric($args[0]) && !defined("PROJECT_ID")) throw new Exception('No project_id provided!');**
```

Yet I am in the control center: redcap/external_modules/manager/control_center.php

There should be no project ID in the URL in the control center at this point. 

redcap_v7.6.10

The JSON for this external file does NOT have "system-settings": [ {"key": "system-project"

Final Issue: Unable to re-enable external module.

**Comment by biggeeves** [comment]
Within the custom external module is a call to REDCap::getData.

```
    private function get_data() {
        // Get the data
        $this->data = REDCap::getData($this->nih_pid, 'array', null, $this->get_fields, null);
    }
```

This method is called during the __construct() abbreviated below:

```
class NIHAnnualReport extends \ExternalModules\AbstractExternalModule {
  __construct() {
        $this->get_data();
         //  more methods called
    }
}
```

I think the module is trying to execute when it is enabled at the system level.  Since it is at the system level, it is missing a pid.  Unfortunately adding pid=58 to the url hides the external module from the list of modules to enable.  Commenting out the line causes other errors to be thrown.  

Below is the csv from the table Module Settings:
```
external_module_id,project_id,key,type,value
1,NULL,version,string,v0.1
2,NULL,version,string,v1.0
3,NULL,enabled,boolean,false
3,NULL,discoverable-in-project,boolean,true
3,58,enabled,boolean,true
3,49,enabled,boolean,true
3,49,report_title,string,"Cumulative Inclusion Enrollment Report"
3,49,report_footer,string,"Study Title: Exploring Cognitive Aging Using Reference Ability Neural Networks"
4,NULL,version,string,v1.1
3,58,report_title,string,"Ha ha ha over-rided."
3,58,report_sub_title,string,"Study Title: Exploring Cognitive Aging ' .                 'Using Reference Ability Neural Networks"
3,58,report_footer,string,"Custom report Footer"
3,58,sex,string,sex
3,58,race,string,r1
3,58,ethnicity,string,r1
3,58,male,string,1
3,58,female,string,2
2,58,enabled,boolean,true

```

ps: What should I change in the MySQL table to work around this as I can't figure out another work around to enable the module and continue development/testing.

**Comment by 123andy** [comment]
I think there is room here for a 'faq/wiki' about how to use the __constructor in the main extended abstract module.  I started down the path of trying to use the __constructor and then just backed away for fear of potential side-effects...  Any musings, @mmcev106, on the role of constructors?

**Comment by mmcev106** [comment]
In this case I'm guessing the problem is just that the parent::__constructor() is not being called.

I personally have not encountered a need for using a module's constructor yet, so I haven't spent too much time thinking about this.  My initial thought is that putting code in a module's constructor is odd since the timing for calling a constructor is undefined.  In general, we view the entry points of a module being the hook methods, since the timing of hook calls are clearly defined, and variables passed into each hook method are typically needed to perform significant actions anyway.

**Comment by taylorr4** [comment]
Note: there is already a section on the documentation page in the testing branch about using the constructor.
