### ISSUE TITLE
In support of supporting config.yaml...

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#62]
So, I've been digging around the various url functions and looking into NOAUTH and the API endpoint.  I was curious about how security was handled and in what cases REDCap is enforcing pid-based authentication and when it isn't...  After seeing the no-auth-pages section of the config.json file, I am hoping to renew the idea of YAML...

I did a little research and it seems that symphony yaml is one of the most mature/robust php yaml parsers out there:
http://symfony.com/doc/current/components/yaml.html

It would offer two major advantages:
1) The ability to include instructions in the default config.yaml file that explain how each option is used, give examples, and talk about potential gotchas.
2) It is much easier read than json

What about checking if a config.yaml file is present, if so, parse it.  If not, the check for config.json as it currently does...  Any opposition or other thoughts?

**Comment by taylorr4** [comment]
@123andy, i think yaml is generally fine, and i like the idea of being able to use comments, but does yaml offer the kind of nesting capabilities that json offers for some of the complex sub-settings and things for modules? Just checked that website, and it seems that it does. I'm not against the idea of using yaml, so if you want to try it out as an alternative, that seems okay to me.

**Comment by 123andy** [comment]
So, I used composer to install it but it puts it into a /vendor/ folder that isn't being checked into the current repo...  How are you guys dealing with composer?  Should I check the current version into the /classes folder?  
-A

**Comment by mmcev106** [comment]
Please forgive the pushback Andy, but considering we're pretty much at (if not past) our limit of what we can support at present, I want to think very carefully about adding any new features and increasing complexity.  While I personally prefer YAML to JSON as well, JSON is much more widely used.  If the percentage of module authors that would actually use YAML is very low, this may not be worth adding...

**Comment by 123andy** [comment]
I agree that Composer doesn't belong.  If I find the time, I'll give it a shot to throw in the YAML class and see if it works.  I hear what you're saying Mark...  maybe not a huge add...

**Comment by mmcev106** [comment]
I might close this for now.  Feel free to re-open at any point.
