### ISSUE TITLE
PAGE Global value for External modules is different 

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#67]
The value for PAGE usually excludes some of the URL.  The REDCap root folder and version are included in the PAGE value for external modules manager.

Example:

Expected value of PAGE: 
ExternalModules/manager/project.php?pid=1

Actual value of PAGE: 
redcap/redcap_v8.0.2/ExternalModules/manager/project.php?pid=1

Examples values for PAGE from other pages. 

- redcap/index.php 
-  index.php 
-  redcap/external_modules/manager/control_center.php 
-  ProjectSetup/index.php 
-  Calendar/index.php 
-  DataExport/index.php 
-  Logging/index.php 
-  DataQuality/field_comment_log.php 
-  UserRights/index.php 
-  DataAccessGroups/index.php 
-  Locking/locking_customization.php 
-  Locking/esign_locking_management.php 
-  DataQuality/index.php 
-  API/project_api.php 
-  API/playground.php 
-  MobileApp/index.php

And the value of PAGE for external modules:
redcap/redcap_v8.0.2/ExternalModules/manager/project.php?pid=1

Possible solution: Use the standardized PAGE format:
ExternalModules/manager/project.php?pid=1

**Comment by mmcev106** [comment]
This sounds like a good change to me.  We discussed something similar a few months ago, but it got tabled because it may require refactoring of a couple of internal modules that expect the current behavior.  It might be difficult to carve out some time for that refactoring, but we can and should make it happen if this is or becomes a priority.

**Comment by mmcev106** [comment]
This has not come up again, which means the current behavior is here to stay unless someone can justify the time to revisit it.  Closing, but feel free to re-open if anyone is able to look into this.
