### ISSUE TITLE
EM throwing errors when exiting during a hook

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#69]
I have a use case where I want to use the redcap_every_page_before_render hook to completely overwrite the redcap response.   So, I don't want to 'return' at the end of my hook but rather exit().  This seems to cause the EM to assume there was a crash and throw an error with the very fancy register shutdown function stuff... (or so I think - never used that before).

So, is there a way I can prevent the error and still exit out of my hook and prevent any further action on that page?

One hack around is something like this:  Thoughts?   I know we have a few hooks that rely on this heavy-handed kind of takeover for a script...

So, in my hook I might have:
```php
function hook_every_page_before_render($project_id = null)
{
    // Util::log(PAGE, "hook_every_page_top");
    if (PAGE == "surveys/index.php" && isset($_GET['IVEM'])) {
        ...
        $GLOBALS['EXTERNAL_MODULE_SHUTDOWN_SUPPRESSION'] = true;
        exit();
}
```

then in the external module:
```php
if(!self::isLocalhost()){
     register_shutdown_function(function(){
          $activeModulePrefix = self::getActiveModulePrefix();

          global $EXTERNAL_MODULE_SHUTDOWN_SUPPRESSION;
          if ($activeModulePrefix == null ||  $GLOBALS['EXTERNAL_MODULE_SHUTDOWN_SUPPRESSION'] == true){
               // A fatal error did not occur in the middle of a module operation.
               return;
          }

          $error = error_get_last();
          if ($error == null) {
          $message = "The '$activeModulePrefix' module was automatically disabled because of a failed shutdown\n";
          $message .= "While no error message was reported, it is likely a module silently failed or 'exit()' or\n";
          $message .= "'die();' was used in the module.  Modules should exit with a 'return'.  To override this\n";
          $message .= "message see the External Module documentation re: \$EXTERNAL_MODULE_SHUTDOWN_SUPPRESSION";
      } else {
          $message = "The '$activeModulePrefix' module was automatically disabled because of the following error:\n\n";
          $message .= 'Error Message: ' . $error['message'] . "\n";
          $message .= 'File: ' . $error['file'] . "\n";
          $message .= 'Line: ' . $error['line'] . "\n";
      }
```

Thoughts?

**Comment by 123andy** [comment]
Or, if error_get_last is empty, should we just skip the shutdown error?

**Comment by mmcev106** [comment]
That definitely seems like a useful feature.  We could have an `AbstractExternalModule::exit()` function so users could just call `$this->exit()`.  That would abstract away any details of how the exit happens, which would give us the freedom to refactor in the future without having to change existing modules.

**Comment by mmcev106** [comment]
One reason I'm not sure we should allow calling exit() directly is that External Module execution order is undefined.  In `AbstractExternalModule::exit()`, we could allow all modules to finish executing for the current hook before exiting.  I think that would be the only way to get consistent behavior.  I don't think we want to give modules the ability to prevent other modules from running.

**Comment by 123andy** [comment]
I love your idea for $this->exit();  I understand the order issue - I think this has to just be user-beware.  Maybe the documentation should suggest that one uses the delayModuleExecution() - I've never tried it.    In the use cases we have, it is assumed that you have validated via the PAGE/query string that this is a unique hit for the redcap_every_page_before_render hook so execution order doesn't matter. 

Can we make it so!

**Comment by mmcev106** [comment]
I think it can be implemented to allow all other modules to finish before exiting, so we should be safe regardless.  This is a pretty big limitation, and should be a fairly quick fix.  I will try to carve out some time for it before the new year.

**Comment by mmcev106** [comment]
I just added an **AbstractExternalModule::exitAfterHook()** method in commit [c8de048](https://github.com/vanderbilt/redcap-external-modules/commit/c8de048536530a4bc65f27bd4e4b4dd0a46af5f4).  Search [the documentation](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/official-documentation.md) for the word "exit" for details.  I believe this will provide the functionality you were hoping for.  Let me know if you see any potential issues or alternate solutions.
