### ISSUE TITLE
Handling quotes / json in config editor for External Modules

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#70]
If you have a text field in config.json of type 'json' and you include quotes, as in:
```
{ "foo" : "bar" }
```
And then save it and edit it again, you see the html escaped version:
```
{ &quot;foo&quot;:&quot;bar&quot; }
```
This makes it harder to edit an actual json string.  Thoughts on having a better json option?

A proposed fix (without knowing if this will break other things:
```javascript
ExternalModules.Settings.prototype.getInputElement = function(type, name, value, inputAttributes){
	if (typeof value == "undefined") {
		value = "";
	}
	if (type == "file") {
		if (ExternalModules.PID) {
			return this.getProjectFileFieldElement(name, value, inputAttributes);
		} else {
			return this.getSystemFileFieldElement(name, value, inputAttributes);
		}
	} else {
		// Modified way to create elements to preserve formatting
		var i = $('<input>').attr('type', type).attr('name',name).attr('value', value).addClass('external-modules-input-element').attr(inputAttributes);
		return $('<p>').append(i.eq(0)).html();
                // return '<input type="' + type + '" name="' + name + '" value="' + this.getAttributeValueHtml(value) + '" ' + this.getElementAttributes({"class":"external-modules-input-element"},inputAttributes) + '>';
	}
}
```
Thoughts?

**Comment by mmcev106** [comment]
That unnecessary escaping does seem quite annoying.   At the moment I'm not sure if bypassing the HTML escaping in **getAttributeValueHtml()** creates any security holes.  I will look into this further and get back to you.

**Comment by mmcev106** [comment]
I just replaced `getAttributeValueHtml()` and all it's references in favor of the escaping method you suggested:

https://github.com/vanderbilt/redcap-external-modules/commit/c98bbf7e131ffa4beeefccdd3c15e308e2fea85d

Thanks very much for pointing this out!
