### ISSUE TITLE
Round out functionality for setting multiple settings at once

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#71]
From Jonathan Swafford:

> 1)	I see a getProjectSettings method to get all project settings. Would it be possible to add a method getSystemSettings to get all system settings?
> 2)	I see a getSubSettings method that gets Project sub settings. Do you think support will be added to get System sub settings?
> 3)	Also, is there a way to set sub settings (Project or System)?
> 

I think these could all be easily implemented.

**Comment by 123andy** [comment]
@swaffoja Does 'getProjectSettingsAsArray' work for the read part?

In some of our more 'complex' external modules, I'm currently using an ACE-mediated JSON editor to set the config.  It isn't as user friendly, but works nicely for development with a lot of flexibility:

<img width="764" alt="2017-12-14_0833" src="https://user-images.githubusercontent.com/7461553/34003234-a64b8d6c-e0a9-11e7-9754-dd13c95f6b41.png">

Happy to share if it helps...

**Comment by swaffoja** [comment]
I think for the first item in my list the `AbstractExternalModule` class just needs a new method called `getSystemSettings` that calls the existing `ExternalModules->getSystemSettingsAsArray(...)`. That should only take 2 minutes and I'll probably submit a PR this weekend.

Getting and setting project/system subsettings seems a bit more complex. The functionality exists in the REDCap UI, it just needs to be exposed to developers via the `AbstractExternalModule` class.

I'd be curious to see how you are using an ACE-mediated JSON editor to set the config. I haven't heard about ACE before. It sounds like you might have a page with an inline JSON editor that saves project or system settings on save?

**Comment by 123andy** [comment]
Hi @swaffoja - I made a dummy EM that has the ace editor. 

https://github.com/susom/redcap-em-ace-config-editor-template

It would be cook for mycap to have a new action-tag called @JSON or something that converts a textarea into an ACE editor with json syntax.  It would allow people to view the data stored in REDCap from mycap in json format in a much more intuitive format...  I'm happy to take a shot at it too...

**Comment by swaffoja** [comment]
@123andy I tried it out. Looks sweet!

I think an ACE editor for a JSON textarea would be beneficial to many different projects, not just MyCap. I think you could make a separate EM called "Extended Action Tags" (or whatever) that implements your editor. People could contribute additional action tags to the repo. MyCap would recommend that Extended Action Tags is installed. I'd make sure all the JSON fields that MyCap creates utilize your @json (or @eat-json?) action tag. 

<img width="805" alt="i" src="https://user-images.githubusercontent.com/887384/34056246-e00de150-e197-11e7-9ae4-ba35bcdfcf16.png">

**Comment by tbembersimeao** [comment]
Hey guys, I'm not sure if this helps, but I'm sharing below a code that I've used in a few modules already, which is pretty useful for me as a developer. It basically displays all the configuration hierarchically - so the sub-settings are nested to their parents.

`ExternalModules.php` of a given module:
``` php
    /**
     * Formats settings into a hierarchical key-value pair array.
     *
     * @param int $project_id
     *   Enter a project ID to get project settings.
     *   Leave blank to get system settings.
     *
     * @return array $formmated
     *   The formatted settings.
     */
    function getFormattedSettings($project_id = null) {
        $config = $this->getConfig();

        if ($project_id) {
            $type = 'project';
            $settings = ExternalModules::getProjectSettingsAsArray($this->PREFIX, $project_id);
        }
        else {
            $type = 'system';
            $settings = ExternalModules::getSystemSettingsAsArray($this->PREFIX);
        }

        $formatted = array();
        foreach ($config[$type . '-settings'] as $field) {
            $key = $field['key'];

            if ($field['type'] == 'sub_settings') {
                // Handling sub settings.
                $formatted[$key] = array();

                if ($field['repeatable']) {
                    // Handling repeating sub settings.
                    foreach (array_keys($settings[$key]['value']) as $delta) {
                        foreach ($field['sub_settings'] as $sub_setting) {
                            $sub_key = $sub_setting['key'];
                            $formatted[$key][$delta][$sub_key] = $settings[$sub_key]['value'][$delta];
                        }
                    }
                }
                else {
                    foreach ($field['sub_settings'] as $sub_setting) {
                        $sub_key = $sub_setting['key'];
                        $formatted[$key][$sub_key] = reset($settings[$sub_key]['value']);
                    }
                }   
            }   
            else {
                $formatted[$key] = $settings[$key]['value'];
            }   
        }   
        
        return $formatted;
    }
```

Return example:
```
Array
(
    [helper_text] => Helper text
    [email_contents] => Array
        (
            [recipient] => example@example.com
            [subject] => Test
            [body] => This is a test
        )
    [contacts] => Array
        (
            [0] => Array
                (
                    [firstname] => Joe
                    [lastname] => Doe
                )
            [1] => Array
                (
                    [firstname] => Janie
                    [lastname] => Doe
                )
        )
)
```

If you guys think that's useful, I'll adapt it to the core, and create a pull request.

**Comment by mmcev106** [comment]
Heh, Travis (another developer on my team) just made something very similar to this.  We were thinking of replacing the getSubSettings() implementation with it.

**Comment by mmcev106** [comment]
This feature seems important enough that it should probably be the default behavior of getSubSettings().  Off the top of your head, do you happen to know if it would be backward compatible to replace the getSubSettings() implementation with this one?

**Comment by tbembersimeao** [comment]
@mmcev106 I think that won't be a problem.

**Comment by mmcev106** [comment]
I still haven't found the time to assess the risks involved in changing this implementation out, and I'm not sure if/when that will happen...  I did recently write a simple unit test for getSubSettings() in order to fix another issue.  I would need more time to make sure it covers all the cases involved in this change though.

**Comment by mmcev106** [comment]
getSubSettings() now supports complex nesting:

https://github.com/vanderbilt/redcap-external-modules/pull/162

**Comment by 123andy** [comment]
Any thoughts on setSubSettings or how that should work?  I'm in a use case where I want to be able to do this...

Alternates would be  'addSubSetting', 'removeSubSetting' or 'updateSubSetting'

What happens if you have a key in your data that isn't defined in your config.json - should that issue a failure?

**Comment by mmcev106** [comment]
I could see setSubSettings() working very similarly to getSubSettings() when it comes to looping through the config.  Currently getSubSettings() is dependent on settings being in config.json for detecting the appropriate array structure, but we could potentially pass in a PHP defined configuration structure as an argument.

Now that I think it through, I think supporting setSubSettings() for settings not in config.json is a bad idea.  I think it might be more appropriate just to store a PHP array (which is currently supported, and serialized to JSON under the hood).

**Comment by mmcev106** [comment]
Closing, since this hasn't been updated in a while.  Feel free to reopen.
