### ISSUE TITLE
Add a hidden or protected attribute to system & project settings

### ISSUE THREAD

**Issue by swaffoja** [vanderbilt/redcap-external-modules#72]
I have system and project settings that should only be altered programmatically via my module. How about a `hidden` or `protected` attribute that would hide the setting from the standard REDCap UI?

```
"system-settings": [{
    "key": "my-super-important-key",
    "name": "The world will end if you alter this!",
    "required": true,
    "type": "text",
    "hidden": true
}]
```

**Comment by mmcev106** [comment]
The settings defined in config.json are actually ONLY for displaying in the UI.  You can (and we frequently do) store all kinds of settings without listing them in config.json.

**Comment by mmcev106** [comment]
I just added the follow note to the documentation to hopefully clarify this for others:

https://github.com/vanderbilt/redcap-external-modules/commit/7ff67a744a1d8db3ea650977dce0f11b345f8446

**Comment by swaffoja** [comment]
Ah, don't know why I didn't think of that. Thanks for the note.
