### ISSUE TITLE
Documentation standard

### ISSUE THREAD

**Issue by pbchase** [vanderbilt/redcap-external-modules#77]
Would it help to define a documentation standard for REDCap modules? In response to @taylorr4's call for providing documentation with modules, we made some revisions to some new modules currently in review. I like what we've done, but I see problems ahead.

In the first iteration we added some text in the description with hyperlinks to the root of the github repos.  E.g.

> This module does useful stuff.  See the complete <b><a href='https://github.com/ctsit/field_notes_display' target='_blank'>documentation</a></b> at <a href='https://github.com/ctsit/field_notes_display' target='_blank'>https://github.com/ctsit/field_notes_display</a>.

The problems with that is these modules will rev. New features will be added and the documentation at the root of the repo on github will reflect the new features. People with an early version of the software will see the modern docs and might be confused by them. To address this I have a new iteration of the "documentation standard" wherein we reference a specific tag. 

> This module does useful stuff.  See the complete <b><a href='https://github.com/ctsit/field_notes_display/tree/1.0.0' target='_blank'>documentation</a></b> at <a href='https://github.com/ctsit/field_notes_display/tree/1.0.0' target='_blank'>https://github.com/ctsit/field_notes_display/tree/1.0.0</a>.

This would hold a module's documentation at the same version as the tagged code. However it does require you to tag your code and update the tags in the description field of config.json on each release. This is doable, but it feels like an opportunity for errors. 

I'd much rather have a documentation standard akin to Github's that would make it very easy to keep the documents and the code in sync. So why not make it _very much_ like Github's standard? We could specify that a README.md at the root of the repo cause a link labeled "Documentation", "More info", or some such to appear with the description.  If clicked the README.md would be processed via Markdown (or MultiMarkdown or Parsedown) and to create an html. The html could be presented in a popup or new window. Any links on that page to other points in the module's folder would result in those documents be presented, perhaps even processed via the Markdown as well. 

This would give the author the ability to package the docs with the code, to link out to other document repositories, or a mix of both. Local documents could be a simple page or multiple pages. They could include images and other file types.

**Comment by taylorr4** [comment]
@pbchase, this is a very timely discussion as @mmcev106 just added a new "documentation" attribute to config.json just yesterday. See https://github.com/vanderbilt/redcap-external-modules/commit/5249b64484fe00e89c233ac0df28e9bd7041a1c2 for the full changes. If you have a readme file included, it will automatically create a link to it in REDCap, or else you can explicitly define it as seen below. I imagine this will go into the official REDCap release in the next couple weeks.

``` json
{
    "documentation": "README.pdf"
}
```
``` json
{
   "documentation": "https://github.com/ctsit/field_notes_display"
}
```

**Comment by mmcev106** [comment]
Search [the documenation](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/official-documentation.md) for the word "README" for a quick description of how this functionality works.  It's not too far off from what you described, and is compatible with GitHub's README.md standard.  I'm going to close this for now, but let us know if you have any followup thoughts.

**Comment by pbchase** [comment]
That looks great, Mark. Thanks for the fix!
