### ISSUE TITLE
View Documentation feature fails with relative links

### ISSUE THREAD

**Issue by pbchase** [vanderbilt/redcap-external-modules#81]
The View Documentation link for REDCap Modules (Added in REDCap 8.2.0) cannot handle relative links in markdown files. E.g., README.md for the [Imagemap Module](https://github.com/ctsit/imagemap) will not display correctly. The images display as broken links. View Source on that page reveals relative links that cannot be resolved:

`<img src="./img/painmap_female.png" alt="PAINMAP_FEMALE" />`

**Comment by mmcev106** [comment]
I just made a change that I believe will solve this:

https://github.com/vanderbilt/redcap-external-modules/commit/48808fbe61b152e19e4a70264f0a814ba0351b48

Feel free to reopen this if you encounter any other cases that aren't working properly.

**Comment by pbchase** [comment]
That might do the trick. Thanks, @mmcev106
