### ISSUE TITLE
Client side module objects

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#88]
We have encountered multiple cases where a client side module object would be useful.  I am considering building this out for part of the logging solution I'm working on, and I'd like to get some input on the structure/syntax.  I'm picturing a javascript object being automatically generated for each module that could be accessed as follows:

`Vanderbilt.SomeExternalModule.log(message)`

The top level javascript object ("Vanderbilt" in the above example) could match the PHP namespace, and the child object could match the module class name ("SomeExternalModule" in the above example).  There could be some built in methods (like logging), and a simple way to add arbitrary methods/variables (perhaps just monkey patching them into the object).

What are your thoughts?

@123andy, @tbembersimeao, @pbchase

**Comment by 123andy** [comment]
I think a javascript object that is analogous to the php one would be a neat idea...  In Shazam, I sent all client-side debugging to 'Shazam.log()' and tried to add some wrappers to handle old browsers where console.log isn't defined, etc.  It also made it easy for me to comment out one line and have the debugging shut off (as opposed to digging through all the console.logs..

Another thing I want to do often is take php variables and push them to javascript.  Perhaps there could be a javascript bin that is present in the AbstractExternalModule instance.  You could do stuff like:

$module->js->foo = json_encode($arr_foo);

Then, to push it to the client you'd have a $moduile->js->render() or something like that... This would push the object (could be named the same as the EM), set some variables, and also include some default functions like the logger...

**Comment by 123andy** [comment]
I should add one place where I would like to be able to include javascript more easily is in the config editor - it would be nice to just be able to insert a js file and call a method when the config is rendered (maybe this is new possible with some of the new hooks).  The alternate method is to add a field to config and then specify the js source but it is awkward to mess with the entire config from a single field.

**Comment by mmcev106** [comment]
Closing, since a basic version of this has been implemented via the `initializeJavascriptModuleObject()` method.  We can hopefully build on it over time.

@123andy, if you're still interested in the settings js idea you mentioned, would you mind opening a separate issue for it with a few more details?
