### ISSUE TITLE
Ideas about error handling on an External Module

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#90]
So, I've got a few ideas about external module error handling...

1) When an error occurs, I wonder if the external module should write to the settings table with the details of the error.  This way you could easily identify which if your modules were enabled but have been shut down due to an error.  Presumably this is something you need to address as people could have production projects depending on these modules.

`key=last-error, type=json-object, value = {"timestamp":"..","project_id":"..", etc...} `

In the Enable External Modules - these modules should be distinguished from modules you haven't enabled.
 
2) When testing/developing, I was thinking about adding the ability to override and prevent the 'auto-disable' feature for an external module when an error occurs.  Perhaps both at a project-level and globally.  This too could be done by adding a certain setting to the table..

`key=continue-on-errors,type=boolean, value=true`

Anyone see any issues with this?

**Comment by 123andy** [comment]
Maybe this is a bad idea..  I'm just looking around the ExternalModule class and seeing the many different ways errors are handled and escalated based on context and user...  This might need some more thought...

**Comment by mmcev106** [comment]
I'm sure there is room for improvement.  While we've made tweaks here an there, the design around error handling is fairly basic and has not been revisited since early prototypes.

**Comment by mmcev106** [comment]
Closing in favor of #218
